// ==UserScript==
// @name         Bingo Search!
// @homepageURL  https://github.com/WellWells/BingoSearch/
// @version      20240123.2
// @description  Give me some good luck
// @author       WellsTsai
// @include      https://www.google.com/search*
// @run-at       document-start
// ==/UserScript==

;(function () {
  'use strict'

  // Rule: Name, URL, PARTIAL_MATCH

  // STOCK
  const STOCK_URL = 'https://goodinfo.tw/tw/StockDetail.asp?STOCK_ID='
  const STOCK_IDs = ['0050', '2258', '1101', '1102', '1103', '1104', '1108', '1109', '1110', '1201', '1203', '1210', '1213', '1215', '1216', '1217', '1218', '1219', '1220', '1225', '1227', '1229', '1231', '1232', '1233', '1234', '1235', '1236', '1256', '1301', '1303', '1304', '1305', '1307', '1308', '1309', '1310', '1312', '1313', '1314', '1315', '1316', '1319', '1321', '1323', '1324', '1325', '1326', '1337', '1338', '1339', '1340', '1341', '1402', '1409', '1410', '1413', '1414', '1416', '1417', '1418', '1419', '1423', '1432', '1434', '1435', '1436', '1437', '1438', '1439', '1440', '1441', '1442', '1443', '1444', '1445', '1446', '1447', '1449', '1451', '1452', '1453', '1454', '1455', '1456', '1457', '1459', '1460', '1463', '1464', '1465', '1466', '1467', '1468', '1470', '1471', '1472', '1473', '1474', '1475', '1476', '1477', '1503', '1504', '1506', '1507', '1512', '1513', '1514', '1515', '1516', '1517', '1519', '1521', '1522', '1524', '1525', '1526', '1527', '1528', '1529', '1530', '1531', '1532', '1533', '1535', '1536', '1537', '1538', '1539', '1540', '1541', '1558', '1560', '1568', '1582', '1583', '1587', '1589', '1590', '1592', '1598', '1603', '1604', '1605', '1608', '1609', '1611', '1612', '1614', '1615', '1616', '1617', '1618', '1626', '1701', '1702', '1707', '1708', '1709', '1710', '1711', '1712', '1713', '1714', '1717', '1718', '1720', '1721', '1722', '1723', '1724', '1725', '1726', '1727', '1730', '1731', '1732', '1733', '1734', '1735', '1736', '1737', '1760', '1762', '1773', '1776', '1783', '1786', '1789', '1795', '1802', '1805', '1806', '1808', '1809', '1810', '1817', '1903', '1904', '1905', '1906', '1907', '1909', '2002', '2006', '2007', '2008', '2009', '2010', '2012', '2013', '2014', '2015', '2017', '2020', '2022', '2023', '2024', '2025', '2027', '2028', '2029', '2030', '2031', '2032', '2033', '2034', '2038', '2049', '2059', '2062', '2069', '2101', '2102', '2103', '2104', '2105', '2106', '2107', '2108', '2109', '2114', '2115', '2201', '2204', '2206', '2207', '2208', '2227', '2228', '2231', '2233', '2236', '2239', '2241', '2243', '2247', '2301', '2302', '2303', '2305', '2308', '2312', '2313', '2314', '2316', '2317', '2321', '2323', '2324', '2327', '2328', '2329', '2330', '2331', '2332', '2337', '2338', '2340', '2342', '2344', '2345', '2347', '2348', '2349', '2351', '2352', '2353', '2354', '2355', '2356', '2357', '2358', '2359', '2360', '2362', '2363', '2364', '2365', '2367', '2368', '2369', '2371', '2373', '2374', '2375', '2376', '2377', '2379', '2380', '2382', '2383', '2385', '2387', '2388', '2390', '2392', '2393', '2395', '2397', '2399', '2401', '2402', '2404', '2405', '2406', '2408', '2409', '2412', '2413', '2414', '2415', '2417', '2419', '2420', '2421', '2423', '2424', '2425', '2426', '2427', '2428', '2429', '2430', '2431', '2433', '2434', '2436', '2438', '2439', '2440', '2441', '2442', '2443', '2444', '2448', '2449', '2450', '2451', '2453', '2454', '2455', '2456', '2457', '2458', '2459', '2460', '2461', '2462', '2464', '2465', '2466', '2467', '2468', '2471', '2472', '2474', '2476', '2477', '2478', '2480', '2481', '2482', '2483', '2484', '2485', '2486', '2488', '2489', '2491', '2492', '2493', '2495', '2496', '2497', '2498', '2499', '2501', '2504', '2505', '2506', '2509', '2511', '2514', '2515', '2516', '2520', '2524', '2527', '2528', '2530', '2534', '2535', '2536', '2537', '2538', '2539', '2540', '2542', '2543', '2545', '2546', '2547', '2548', '2597', '2601', '2603', '2605', '2606', '2607', '2608', '2609', '2610', '2611', '2612', '2613', '2614', '2615', '2616', '2617', '2618', '2630', '2633', '2634', '2636', '2637', '2642', '2701', '2702', '2704', '2705', '2706', '2707', '2712', '2722', '2723', '2727', '2731', '2739', '2748', '2801', '2809', '2812', '2816', '2820', '2823', '2832', '2834', '2836', '2838', '2841', '2845', '2849', '2850', '2851', '2852', '2855', '2867', '2880', '2881', '2882', '2883', '2884', '2885', '2886', '2887', '2888', '2889', '2890', '2891', '2892', '2897', '2901', '2903', '2904', '2905', '2906', '2908', '2910', '2911', '2912', '2913', '2915', '2923', '2929', '2936', '2939', '3002', '3003', '3004', '3005', '3006', '3008', '3010', '3011', '3013', '3014', '3015', '3016', '3017', '3018', '3019', '3021', '3022', '3023', '3024', '3025', '3026', '3027', '3028', '3029', '3030', '3031', '3032', '3033', '3034', '3035', '3036', '3037', '3038', '3040', '3041', '3042', '3043', '3044', '3045', '3046', '3047', '3048', '3049', '3050', '3051', '3052', '3054', '3055', '3056', '3057', '3058', '3059', '3060', '3062', '3090', '3094', '3130', '3149', '3164', '3167', '3189', '3209', '3229', '3231', '3257', '3266', '3296', '3305', '3308', '3311', '3312', '3321', '3338', '3346', '3356', '3376', '3380', '3383', '3406', '3413', '3416', '3419', '3432', '3437', '3443', '3450', '3454', '3481', '3494', '3501', '3504', '3515', '3518', '3528', '3530', '3532', '3533', '3535', '3536', '3543', '3545', '3550', '3557', '3563', '3576', '3583', '3588', '3591', '3593', '3596', '3605', '3607', '3617', '3622', '3645', '3653', '3661', '3665', '3669', '3673', '3679', '3682', '3686', '3694', '3698', '3701', '3702', '3703', '3704', '3705', '3706', '3708', '3711', '3712', '4104', '4106', '4108', '4119', '4133', '4137', '4141', '4142', '4148', '4155', '4164', '4190', '4306', '4414', '4426', '4438', '4439', '4526', '4532', '4536', '4540', '4545', '4551', '4552', '4555', '4557', '4560', '4562', '4564', '4566', '4571', '4572', '4576', '4581', '4720', '4722', '4725', '4737', '4739', '4746', '4755', '4763', '4764', '4766', '4807', '4904', '4906', '4912', '4915', '4916', '4919', '4927', '4930', '4934', '4935', '4938', '4942', '4943', '4952', '4956', '4958', '4960', '4961', '4967', '4968', '4976', '4977', '4989', '4994', '4999', '5007', '5203', '5215', '5225', '5234', '5243', '5258', '5264', '5269', '5283', '5284', '5285', '5288', '5305', '5388', '5434', '5469', '5471', '5484', '5515', '5519', '5521', '5522', '5525', '5531', '5533', '5534', '5538', '5546', '5607', '5608', '5706', '5871', '5876', '5880', '5906', '5907', '6005', '6024', '6108', '6112', '6115', '6116', '6117', '6120', '6128', '6131', '6133', '6136', '6139', '6141', '6142', '6152', '6153', '6155', '6164', '6165', '6166', '6168', '6172', '6176', '6177', '6183', '6184', '6189', '6191', '6192', '6196', '6197', '6201', '6202', '6205', '6206', '6209', '6213', '6214', '6215', '6216', '6224', '6225', '6226', '6230', '6235', '6239', '6243', '6251', '6257', '6269', '6271', '6277', '6278', '6281', '6282', '6283', '6285', '6288', '6289', '6405', '6409', '6412', '6414', '6415', '6416', '6431', '6442', '6443', '6449', '6451', '6452', '6456', '6464', '6477', '6491', '6504', '6505', '6525', '6531', '6533', '6541', '6552', '6558', '6573', '6579', '6581', '6582', '6591', '6592', '6598', '6605', '6625', '6641', '6655', '6666', '6668', '6669', '6670', '6671', '6672', '6674', '6698', '6706', '6715', '6754', '8011', '8016', '8021', '8028', '8033', '8039', '8046', '8070', '8072', '8081', '8101', '8103', '8104', '8105', '8110', '8112', '8114', '8131', '8150', '8163', '8201', '8210', '8213', '8215', '8222', '8249', '8261', '8271', '8341', '8367', '8374', '8404', '8411', '8422', '8427', '8429', '8442', '8443', '8454', '8462', '8463', '8464', '8466', '8467', '8473', '8478', '8480', '8481', '8482', '8488', '8499', '8926', '8940', '8996', '9802', '9902', '9904', '9905', '9906', '9907', '9908', '9910', '9911', '9912', '9914', '9917', '9918', '9919', '9921', '9924', '9925', '9926', '9927', '9928', '9929', '9930', '9931', '9933', '9934', '9935', '9937', '9938', '9939', '9940', '9941', '9942', '9943', '9944', '9945', '9946', '9955', '9958']
  const STOCK = STOCK_IDs.map((ID) => [ID, STOCK_URL + ID])

  // BANK
  const BANKS = [
    [['一信', '花蓮'], 'https://www.hua215.com.tw'],
    [['一信', '新竹'], 'https://www.hcfcbank.com.tw'],
    [['一信', '彰化'], 'https://chfc.scu.org.tw'],
    [['一信', '澎湖'], 'https://pfcco.scu.org.tw'],
    [['一信', /基隆|淡水/], 'https://www.tfccbank.com.tw'],
    [['二信', '台中'], 'https://www.tsca.com.tw'],
    [['二信', '花蓮'], 'https://www.hl2c.com.tw'],
    [['二信', '基隆'], 'https://www.kscc.com.tw'],
    [['二信', '澎湖'], 'https://ph2c.scu.org.tw'],
    [['人壽', '三商'], 'https://www.mli.com.tw'],
    [['人壽', '台新'], 'https://www.taishinlife.com.tw'],
    [['人壽', '台灣'], 'https://www.taiwanlife.com'],
    [['人壽', '全球'], 'https://www.transglobe.com.tw'],
    [['人壽', '安聯'], 'https://www.allianz.com.tw/zh_TW.html'],
    [['人壽', '宏泰'], 'https://www.hontai.com.tw'],
    [['人壽', '南山'], 'https://www.nanshanlife.com.tw/NanshanWeb'],
    [['人壽', '國泰'], 'https://www.cathaylife.com.tw'],
    [['人壽', '第一'], 'https://www.firstlife.com.tw/FirstWeb'],
    [['人壽', '富邦'], 'https://www.fubon.com/life'],
    [['人壽', '新光'], 'https://www.skl.com.tw'],
    [['人壽', /凱基|中國/], 'https://www.kgilife.com.tw/zh-tw'],
    [['十信', '彰化'], 'https://ch10c.scu.org.tw'],
    [['三信', '台南'], 'https://ttc.scu.org.tw'],
    [['三信', '高雄'], 'https://www.kh3c.com.tw'],
    [['三信', '新竹'], 'https://www.hc3cbank.com.tw'],
    [['三信', '嘉義'], 'https://chiayi3c.scu.org.tw'],
    [['土地', '銀行'], 'https://www.landbank.com.tw/'],
    [['五信', '台北'], 'https://taipei-tfcc.scu.org.tw'],
    [['五信', '彰化'], 'https://fs161.scu.org.tw'],
    [['六信', '彰化'], 'https://www.ch6c.com.tw'],
    [['台灣', '銀行'], 'https://www.bot.com.tw'],
    [['信用', '宜蘭'], 'https://ilan.scu.org.tw'],
    [['信用', '金門'], 'https://kinmen.scu.org.tw'],
    [['信用', '桃園'], 'https://tycbank.scu.org.tw'],
    [['信用', '淡水'], 'https://tsc.scu.org.tw'],
    [['信用', '鹿港'], 'https://lkbank.scu.org.tw'],
    [['商銀', '上海'], 'https://www.scsb.com.tw'],
    [['商銀', '樂天'], 'https://www.rakuten-bank.com.tw'],
    [['銀行', '台中'], 'https://www.tcbbank.com.tw'],
    [['銀行', '高雄'], 'https://www.bok.com.tw/welcome'],
    [['銀行', '彰化'], 'https://www.bankchb.com/frontend/index.html'],
    [['證券', '元大'], 'https://www.yuanta.com.tw'],
    [['證券', '元富'], 'https://www.masterlink.com.tw'],
    [['證券', '台新'], 'https://www.tssco.com.tw'],
    [['證券', '永豐金'], 'https://www.sinotrade.com.tw'],
    [['證券', '玉山'], 'https://www.esunsec.com.tw'],
    [['證券', '兆豐'], 'https://www.emega.com.tw'],
    [['證券', '國泰'], 'https://iweb.cathaysec.com.tw'],
    [['證券', '凱基'], 'https://eoa.kgi.com.tw'],
    [['證券', '富邦'], 'https://www.fbs.com.tw'],
    [['證券', '華南'], 'https://www.entrust.com.tw'],
    [/^(三信)$/i, 'https://cotabank.com.tw'],
    [/^(土銀)$/i, 'https://www.landbank.com.tw'],
    [/^(中國信託|中信)$/i, 'https://www.ctbcbank.com/twrbo/zh_tw/index.html'],
    [/^(元大)$/i, 'https://ebank.yuantabank.com.tw/ib'],
    [/^(台新|richart)$/i, 'https://www.taishinbank.com.tw'],
    [/^(玉山銀行)$/i, 'https://www.esunbank.com/zh-tw/personal'],
    [/^(全盈)$/i, 'https://www.pluspay.com.tw'],
    [/^(富邦金控)$/i, 'https://www.fubon.com'],
    [/^(街口)$/i, 'https://www.jkopay.com'],
    [/^(網路郵局)$/i, 'https://ipost.post.gov.tw/pst/home.html'],
    [/^(歐付寶)$/i, 'https://www.opay.tw'],
    [/^(證券)$/i, 'https://www.twse.com.tw'],
    [/^(ezpay)$/i, 'https://www.ezpay.com.tw'],
    [/台銀(?:銀行)?/i, 'https://www.bot.com.tw'],
    [/永豐(?:銀行)?/i, 'https://mma.sinopac.com/MemberPortal/Member/NextWebLogin.aspx'],
    [/兆豐(?:銀行)?/i, 'https://www.megabank.com.tw'],
    [/合作金/i, 'https://www.tcb-bank.com.tw'],
    [/星展(?:銀行)?/i, 'https://internet-banking.dbs.com.tw'],
    [/國泰(?:銀行)?/i, 'https://www.cathaybk.com.tw/cathaybk'],
    [/富邦(?:銀行)?/i, 'https://ebank.taipeifubon.com.tw/B2C/common/Index.faces'],
    [/渣打(?:銀行)?/i, 'https://www.sc.com/tw'],
    [/華南(?:銀行)?/i, 'https://netbank.hncb.com.tw/netbank/servlet/TrxDispatcher?trx=com.lb.wibc.trx.Login&state=prompt&Recognition=private'],
    [/陽信(?:銀行)?/i, 'https://www.sunnybank.com.tw/net'],
    [/新光(?:銀行)?/i, 'https://www.skbank.com.tw'],
  ]

  const SCHOOL = [
    [[/圖書館/i, /台灣大學|台大|ntu/i], 'https://www.lib.ntu.edu.tw/'],
    [[/圖書館/i, /成大|成功大|ncku/i], 'https://www.lib.ncku.edu.tw/'],
    [/^(台灣大學|台大|ntu)$/i, 'https://www.ntu.edu.tw'],
    [/^(台灣圖書館)$/i, 'https://www.ntl.edu.tw/'],
    [/^(南一中|tnfsh)$/i, 'https://www.tnfsh.tn.edu.tw/'],
    [/^(師範|ntnu)$/i, 'https://www.ntnu.edu.tw'],
    [/^(高雄中學|雄中)$/, 'https://www.kshs.kh.edu.tw/index.php'],
    [/^(國圖|國家圖書館)$/i, 'https://www.ncl.edu.tw/'],
    [/^(清大|清華|nthu)$/i, 'https://www.nthu.edu.tw'],
    [/^中一中$/i, 'https://tcfsh.tc.edu.tw/'],
    [/^北科$|台北科技|北工專|^ntut$/i, 'https://www.ntut.edu.tw'],
    [/^台科$|台灣科|^ntust$/i, 'https://www.ntust.edu.tw'],
    [/^交大$|陽明大|陽明交|^nycu$/i, 'https://www.nycu.edu.tw'],
    [/^成大$|成功大|^ncku$/i, 'https://www.ncku.edu.tw'],
    [/^雲科$|雲林科技/, 'https://www.yuntech.edu.tw'],
    [/中山大|nsysu/i, 'https://www.nsysu.edu.tw/'],
    [/中央大|ncu/i, 'https://www.ncu.edu.tw/tw/'],
    [/台中科|^nutc$/i, 'https://www.nutc.edu.tw/'],
    [/高第一|^高科大$|^高雄科技大學$|^nkust$/i, 'https://www.nkust.edu.tw/'],
  ]

  const GOV = [
    [['公共', '政策'], 'https://join.gov.tw/'],
    [['公車', '台中'], 'https://citybus.taichung.gov.tw/'],
    [['公車', '台北'], 'https://ebus.gov.taipei/'],
    [['公車', '台南'], 'https://2384.tainan.gov.tw/NewTNBusWeb/'],
    [['公車', '桃園'], 'https://ebus.tycg.gov.tw/ebus/'],
    [['公車', '高雄'], 'https://ibus.tbkc.gov.tw/ibus/'],
    [['台灣', '美術'], 'https://www.ntmofa.gov.tw/'],
    [['民政局', '台中'], 'https://demographics.taichung.gov.tw/'],
    [['社會局', '桃園'], 'https://sab.tycg.gov.tw/'],
    [['社會局', '高雄'], 'https://socbu.kcg.gov.tw/'],
    [['政府', '台中'], 'https://www.taichung.gov.tw'],
    [['政府', '台北'], 'https://www.gov.taipei'],
    [['政府', '台東'], 'https://www.taitung.gov.tw'],
    [['政府', '台南'], 'https://www.tainan.gov.tw'],
    [['政府', '花蓮'], 'https://www.hl.gov.tw'],
    [['政府', '金門'], 'https://www.kinmen.gov.tw'],
    [['政府', '屏東'], 'https://www.pthg.gov.tw'],
    [['政府', '苗栗'], 'https://www.miaoli.gov.tw'],
    [['政府', '桃園'], 'https://www.tycg.gov.tw'],
    [['政府', '高雄'], 'https://www.kcg.gov.tw'],
    [['政府', '基隆'], 'https://www.klcg.gov.tw'],
    [['政府', '連江'], 'https://www.matsu.gov.tw'],
    [['政府', '雲林'], 'https://www.yunlin.gov.tw'],
    [['政府', '新北'], 'https://www.ntpc.gov.tw'],
    [['政府', '新竹'], 'https://www.hccg.gov.tw'],
    [['政府', '嘉義'], 'https://www.chiayi.gov.tw'],
    [['政府', '澎湖'], 'https://www.penghu.gov.tw'],
    [['健康', '存摺'], 'https://myhealthbank.nhi.gov.tw/IHKE3000/IHKE3099S01'],
    [['勞動', '發展'], 'https://www.wda.gov.tw/'],
    [['open', 'data'], 'https://data.gov.tw'],
    [[/發票/i, /中獎|兌獎|開獎/], 'https://invoice.etax.nat.gov.tw/'],
    [[/圖書館/i, /公共/i], 'https://www.nlpi.edu.tw/'],
    [[/圖書館/i, /台中/i], 'https://www.library.taichung.gov.tw/public/'],
    [[/圖書館/i, /台北/i], 'https://tpml.gov.taipei/'],
    [[/圖書館/i, /台南/i], 'https://www.tnpl.tn.edu.tw/'],
    [[/圖書館/i, /桃園/i], 'https://www.typl.gov.tw/zh-tw'],
    [[/圖書館/i, /新北/i], 'https://www.library.ntpc.gov.tw/'],
    [[/圖書館/i, /嘉義/i], 'https://www.cycab.gov.tw/'],
    [[/機場|航空/i, '台中'], 'https://www.tca.gov.tw'],
    [[/機場|航空/i, '台南'], 'https://www.tna.gov.tw'],
    [[/機場|航空/i, '桃園'], 'https://www.taoyuan-airport.com'],
    [[/機場|航空/i, /松山|台北/], 'https://www.tsa.gov.tw'],
    [[/機場|航空/i, /高雄|小港/], 'https://www.kia.gov.tw'],
    [/^(內政部)$/i, 'https://data.gov.tw/'],
    [/^(公平交易委員會)$/i, 'https://www.ftc.gov.tw'],
    [/^(公路總局)$/i, 'https://www.thb.gov.tw'],
    [/^(天文館)$/i, 'https://tam.gov.taipei'],
    [/^(文化部)$/i, 'https://www.moc.gov.tw'],
    [/^(文化幣)$/i, 'https://twcp.moc.gov.tw/'],
    [/^(文學館)$/i, 'https://www.nmtl.gov.tw'],
    [/^(水土保持局)$/i, 'https://www.ardswc.gov.tw'],
    [/^(台鐵)$/i, 'https://www.railway.gov.tw/tra-tip-web/tip'],
    [/^(司法院)$/i, 'https://www.judicial.gov.tw'],
    [/^(外交部)$/i, 'https://www.mofa.gov.tw'],
    [/^(民事訴訟法|民法)$/i, 'https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=B0010001'],
    [/^(立法院)$/i, 'https://www.ly.gov.tw'],
    [/^(交通部)$/i, 'https://www.motc.gov.tw'],
    [/^(刑法)$/i, 'https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=C0000001'],
    [/^(地震)$/i, 'https://www.cwa.gov.tw/V8/C/E/index.html'],
    [/^(考試院)$/i, 'https://www.exam.gov.tw'],
    [/^(考選部)$/i, 'https://wwwc.moex.gov.tw/main/home/wfrmHome.aspx'],
    [/^(行政法)$/i, 'https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=A0030055'],
    [/^(行政院)$/i, 'https://www.ey.gov.tw'],
    [/^(行政訴訟法)$/i, 'https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=A0030154'],
    [/^(法務部)$/i, 'https://www.moj.gov.tw'],
    [/^(法規)$/i, 'https://law.moj.gov.tw'],
    [/^(故宮)$/i, 'https://www.npm.gov.tw'],
    [/^(科工館)$/i, 'https://www.nstm.gov.tw'],
    [/^(科博館)$/i, 'https://www.nmns.edu.tw'],
    [/^(桃機|桃園機場)$/i, 'https://www.taoyuan-airport.com'],
    [/^(氣象局)$/i, 'https://www.cwa.gov.tw'],
    [/^(海巡署)$/i, 'https://www.cga.gov.tw'],
    [/^(航空局)$/i, 'https://www.caa.gov.tw'],
    [/^(航港局)$/i, 'https://www.motcmpb.gov.tw'],
    [/^(財政部)$/i, 'https://www.mof.gov.tw'],
    [/^(高速公路局)$/i, 'https://www.freeway.gov.tw'],
    [/^(健保署)$/i, 'https://www.nhi.gov.tw'],
    [/^(健康署)$/i, 'https://www.hpa.gov.tw'],
    [/^(國史館)$/i, 'https://ahonline.drnh.gov.tw/index.php'],
    [/^(國防部)$/i, 'https://www.mnd.gov.tw'],
    [/^(國科會|科技部|ntsc)$/i, 'https://www.nstc.gov.tw'],
    [/^(國家通訊|ncc)$/i, 'https://www.ncc.gov.tw'],
    [/^(國家發展委員會)$/i, 'https://www.ndc.gov.tw'],
    [/^(國會圖書館)$/i, 'https://npl.ly.gov.tw'],
    [/^(專利)$/i, 'https://gpss1.tipo.gov.tw/gpsskmc/gpssbkm'],
    [/^(教育部)$/i, 'https://www.edu.tw'],
    [/^(移工)$/i, 'https://www.wda.gov.tw/cp.aspx?n=A86C00562D6C92C8'],
    [/^(移民署)$/i, 'https://www.immigration.gov.tw/'],
    [/^(勞動部)$/i, 'https://www.mol.gov.tw'],
    [/^(就業通)$/i, 'https://job.taiwanjobs.gov.tw/'],
    [/^(經濟部)$/i, 'https://www.moea.gov.tw'],
    [/^(農業部)$/i, 'https://www.moa.gov.tw'],
    [/^(電子發票)$/i, 'https://www.einvoice.nat.gov.tw/'],
    [/^(漁業署)$/i, 'https://www.fa.gov.tw'],
    [/^(監理站)$/i, 'https://www.mvdis.gov.tw/?from=mobile#gsc.tab=0'],
    [/^(監察院)$/i, 'https://www.cy.gov.tw'],
    [/^(管制署)$/i, 'https://www.cdc.gov.tw'],
    [/^(衛生福利部|衛福部)$/i, 'https://www.mohw.gov.tw'],
    [/^(憲法)$/i, 'https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=A0000001'],
    [/^(環保署)$/i, 'https://www.moenv.gov.tw'],
    [/^(總統府)$/i, 'https://www.president.gov.tw/'],
    [/^(總圖)$/i, 'https://www.ksml.edu.tw/mainlibrary/'],
    [/^(薪資|薪情)$/i, 'https://earnings.dgbas.gov.tw/experience_sub_01.aspx'],
    [/^(fda)$/i, 'https://www.fda.gov.tw'],
    [/中央選舉|中選會|選舉/, 'https://www.cec.gov.tw'],
  ]

  const TRAVEL = [
    [['東森', '旅遊'], 'https://www.etholiday.com'],
    [['旅遊', '台中'], 'https://travel.taichung.gov.tw'],
    [['旅遊', '台北'], 'https://www.travel.taipei/zh-tw'],
    [['旅遊', '台南'], 'https://www.twtainan.net'],
    [['旅遊', '宜蘭'], 'https://travel.ilantravel.tw'],
    [['旅遊', '花蓮'], 'https://tour-hualien.hl.gov.tw'],
    [['旅遊', '金門'], 'https://kinmen.travel'],
    [['旅遊', '南投'], 'https://travel.nantou.gov.tw'],
    [['旅遊', '高雄'], 'https://khh.travel'],
    [['旅遊', '新北'], 'https://newtaipei.travel/zh-tw/attractions/list'],
    [['旅遊', '新竹'], 'https://tourism.hccg.gov.tw'],
    [['旅遊', '澎湖'], 'https://penghutravel.com'],
    [/^(大億)$/i, 'https://www.tayih.com.tw'],
    [/^(山富)$/i, 'https://www.travel4u.com.tw'],
    [/^(五福)$/i, 'https://www.lifetour.com.tw'],
    [/^(日本航空|日航|jal)$/i, 'https://www.jal.co.jp/tw/zhtw'],
    [/^(可樂)$/i, 'https://www.colatour.com.tw'],
    [/^(立榮|uniair)$/i, 'https://www.uniair.com.tw'],
    [/^(易飛網|ezfly)$/i, 'https://www.ezfly.com'],
    [/^(易遊網|eztravel)$/i, 'https://www.eztravel.com.tw'],
    [/^(東南)$/i, 'https://www.settour.com.tw'],
    [/^(虎行|虎航|tigerair)$/i, 'https://www.tigerairtw.com/zh-tw'],
    [/^(長汎)$/i, 'https://www.everfuntravel.com'],
    [/^(星宇|starlux)$/i, 'https://www.starlux-airlines.com/zh-TW'],
    [/^(國泰航空)$/i, 'https://www.cathaypacific.com/cx/zh_TW.html'],
    [/^(喜鴻)$/i, 'https://www.besttour.com.tw'],
    [/^(華信)$/i, 'https://www.mandarin-airlines.com'],
    [/^(華航)$/i, 'https://www.china-airlines.com/tw/zh'],
    [/^(雄獅)$/i, 'https://www.liontravel.com/category/zh-tw/index'],
    [/^(鳳凰)$/i, 'https://www.travel.com.tw'],
    [/^(樂桃)$/i, 'https://www.flypeach.com/tw'],
    [/^(燦星)$/i, 'https://www.startravel.com.tw'],
    [/^(燦星)$/i, 'https://www.startravel.com.tw/'],
    [/^(agoda)$/i, 'https://www.agoda.com/zh-tw'],
    [/^(airbnb)$/i, 'https://www.airbnb.com.tw'],
    [/^(bmw)$/i, 'https://www.bmw.com.tw/zh/index.html'],
    [/^(booking)$/i, 'https://www.booking.com/index.zh-tw.html'],
    [/^(expedia)$/i, 'https://www.expedia.com.tw'],
    [/^(hotels)$/i, 'https://tw.hotels.com'],
    [/^(kkday)$/i, 'https://www.kkday.com/zh-tw'],
    [/^(klook|客路)$/i, 'https://www.klook.com/zh-TW'],
    [/^(traveloka)$/i, 'https://www.traveloka.com'],
    [/^(trivago)$/i, 'https://www.trivago.com.tw'],
  ]

  const PLACE = [
    [['886', '眷村'], 'https://mingdevillage.khm.org.tw/'],
    [['西湖', '渡假'], 'https://www.westlake.com.tw/'],
    [['東勢', '林場'], 'https://www.tsfa.com.tw/'],
    [['香格里拉', '樂園'], 'https://www.shangrila.com.tw/'],
    [['海洋', '公園'], 'https://www.farglory-oceanpark.com.tw/'],
    [['動物園', '新竹'], 'https://zoo-info.hccg.gov.tw/'],
    [['動物園', /台北|木柵/], 'https://www.zoo.gov.taipei/'],
    [['動物園', /壽山|高雄/], 'https://zoo.kcg.gov.tw/'],
    [['萬瑞', '森林'], 'http://wanruey.weebly.com/'],
    [['澎湖', '水族'], 'https://www.penghu-aquarium.com/'],
    [/^(九九峰)$/i, 'http://www.jojozoopark.com/'],
    [/^(九族)$/i, 'https://www.nine.com.tw/'],
    [/^(小人國)$/i, 'https://www.wow.com.tw/'],
    [/^(小叮噹)$/i, 'https://www.ding-dong.com.tw/'],
    [/^(六福村)$/i, 'https://www.leofoovillage.com.tw/'],
    [/^(木柵)$/i, 'https://www.zoo.gov.taipei/'],
    [/^(水牛城)$/i, 'https://www.732097.com.tw/news/'],
    [/^(火炎山)$/i, 'https://conservation.forest.gov.tw/0000116'],
    [/^(尖山埤)$/i, 'https://www.taisugar.com.tw/resting/jianshanpi/index.aspx'],
    [/^(杉林溪|森林溪)$/i, 'http://www.goto307.com.tw/'],
    [/^(阿里山)$/i, 'https://www.ali-nsa.net/'],
    [/^(茂林)$/i, 'https://www.maolin-nsa.gov.tw/'],
    [/^(泰雅度假)$/i, 'https://www.atayal.com.tw/'],
    [/^(海生館)$/i, 'https://www.nmmba.gov.tw/'],
    [/^(清境)$/i, 'https://www.cingjing.gov.tw/'],
    [/^(野柳海洋)$/i, 'https://www.oceanworld.com.tw/'],
    [/^(雲仙)$/i, 'https://www.yun-hsien.com.tw/'],
    [/^(義大世界)$/i, 'https://www.edathemepark.com.tw/'],
    [/^(頑皮世界)$/i, 'https://www.wanpiworldzoo.com.tw/'],
    [/^(嘉明湖)$/i, 'https://jmlnt.forest.gov.tw/'],
    [/^(壽山)$/i, 'https://zoo.kcg.gov.tw/'],
    [/^(劍湖山)$/i, 'https://www.janfusun.com.tw/fancyworld.php'],
    [/^(澄清湖)$/i, 'https://khh.travel/zh-tw/attractions/detail/9'],
    [/^(麗寶)$/i, 'https://www.lihpaoresort.com/LihpaolandApp/'],
    [/^(寶來)$/i, 'https://www.maolin-nsa.gov.tw/04000067.html'],
    [/^(xpark)$/i, 'https://www.xpark.com.tw/'],
    [/^勝利(新|星)村$/i, 'https://www.cultural.pthg.gov.tw/vipzone/Default.aspx'],
  ]

  const CURE = [
    [['榮總', '台中'], 'https://www.vghtc.gov.tw'],
    [['榮總', '台東'], 'https://www.vhtt.gov.tw'],
    [['榮總', '台南'], 'https://www.vhyk.gov.tw'],
    [['榮總', '屏東'], 'https://www.ptvgh.gov.tw'],
    [['榮總', '桃園'], 'https://www.tyvh.gov.tw'],
    [['榮總', '高雄'], 'https://www.vghks.gov.tw'],
    [['榮總', '新竹'], 'https://org.vghtpe.gov.tw/vhct/'],
    [['醫院', '三軍'], 'https://www.tsgh.ndmctsgh.edu.tw'],
    [['醫院', '大同'], 'https://www.kmtth.org.tw'],
    [['醫院', '小港'], 'https://www.kmsh.org.tw'],
    [['醫院', '中山'], 'https://www.csh.org.tw'],
    [['醫院', '中國'], 'https://www.cmuh.cmu.edu.tw'],
    [['醫院', '台大'], 'https://www.ntuh.gov.tw/ntuh/Index.action'],
    [['醫院', '台南'], 'https://www.tmh.org.tw'],
    [['醫院', '民生'], 'https://www.kmsh.gov.tw'],
    [['醫院', '安南'], 'https://www.tmanh.org.tw'],
    [['醫院', '成大'], 'https://web.hosp.ncku.edu.tw/nckm'],
    [['醫院', '亞東'], 'https://www.femh.org.tw/mainpage/index'],
    [['醫院', '奇美'], 'https://www.chimei.org.tw'],
    [['醫院', '長庚'], 'https://www.cgmh.org.tw'],
    [['醫院', '為恭'], 'https://www.weigong.org.tw'],
    [['醫院', '馬偕'], 'https://www.mmh.org.tw'],
    [['醫院', '國泰'], 'https://www.cgh.org.tw'],
    [['醫院', '凱旋'], 'https://ksph.kcg.gov.tw'],
    [['醫院', '博仁'], 'https://www.pojengh.com.tw'],
    [['醫院', '萬芳'], 'https://www.wanfang.gov.tw'],
    [['醫院', '義大'], 'https://www.edah.org.tw'],
    [['醫院', '慈濟'], 'https://www.tzuchi.com.tw/home'],
    [['醫院', '榮民'], 'https://www.vghtpe.gov.tw'],
    [['醫院', '蕭中正'], 'https://www.hsiaohospital.org'],
    [['醫院', '礦工'], 'http://twmgh.com'],
    [/^(阮綜合)$/i, 'https://www.yuanhosp.com.tw'],
    [/^(郭綜合)$/i, 'https://www.kgh.com.tw'],
    [/^(童綜合)$/i, 'https://www.sltung.com.tw'],
    [/^(榮總)$/i, 'https://www.vghtpe.gov.tw'],
  ]

  const MOTOR = [
    [['cyber', 'truck'], 'https://www.tesla.com/zh_tw/cybertruck'],
    [['model', '3'], 'https://www.tesla.com/zh_tw/model3'],
    [['model', 's'], 'https://www.tesla.com/zh_tw/models'],
    [['model', 'x'], 'https://www.tesla.com/zh_tw/modelx'],
    [['model', 'y'], 'https://www.tesla.com/zh_tw/modely'],
    [['santa', 'fe'], 'https://www.hyundai-motor.com.tw/clicktobuy/santa-fe'],
    [/^(8891)$/i, 'https://www.8891.com.tw'],
    [/^(三菱|mitsubishi)$/i, 'https://www.mitsubishi-motors.com.tw'],
    [/^(三陽|sym)$/i, 'https://tw.sym-global.com'],
    [/^(山葉|yamaha)$/i, 'https://www.yamaha-motor.com.tw'],
    [/^(日產|nissan)$/i, 'https://new.nissan.com.tw'],
    [/^(台鈴|suzuki)$/i, 'https://www.suzukimotor.com.tw'],
    [/^(布加迪|bugatti)$/i, 'https://www.bugatti.com/'],
    [/^(本田|honda)$/i, 'https://www.honda-taiwan.com.tw'],
    [/^(光陽|kymco)$/i, 'https://www.kymco.com.tw'],
    [/^(找車網|findcar)$/i, 'https://www.findcar.com.tw'],
    [/^(和泰|hotai)$/i, 'https://pressroom.hotaimotor.com.tw/zh/'],
    [/^(法拉利|ferrari)$/i, 'https://www.ferrari.com/zh-CN'],
    [/^(保時捷|porsche)$/i, 'https://www.porsche.com/taiwan/zh-tw/'],
    [/^(特斯拉|tesla)$/i, 'https://www.tesla.com/zh_tw'],
    [/^(馬自達|mazda)$/i, 'https://www.mazda.com.tw'],
    [/^(得利卡|delica)$/i, 'https://www.mitsubishi-motors.com.tw/delica'],
    [/^(富豪|volvo)$/i, 'https://www.volvocars.com/tw'],
    [/^(奧迪|audi)$/i, 'https://www.audi.com.tw/tw/web/zh.html'],
    [/^(瑪莎拉蒂|maserati)$/i, 'https://www.maserati.com/tw/zh'],
    [/^(福特|ford)$/i, 'https://www.ford.com.tw'],
    [/^(福斯|volkswagen)$/i, 'https://www.volkswagen.com.tw/zh.html'],
    [/^(賓士|benz)$/i, 'https://www.mercedes-benz.com.tw/passengercars.html'],
    [/^(賓利|bentley)$/i, 'https://www.bentleymotors.com/tw/zh/tw-campaign-home.html'],
    [/^(鴻華|foxtronev)$/i, 'https://www.foxtronev.com/tw/'],
    [/^(藍寶堅尼|蘭博基尼|lamborghini)$/i, 'https://www.lamborghini.com/cn-en'],
    [/^(豐田|toyota)$/i, 'https://www.toyota.com.tw'],
    [/^(alphard)$/i, 'https://www.toyota.com.tw/showroom/ALPHARD'],
    [/^(altis)$/i, 'https://www.toyota.com.tw/showroom/ALTIS'],
    [/^(camry)$/i, 'https://www.toyota.com.tw/showroom/CAMRY'],
    [/^(corolla)$/i, 'https://www.toyota.com.tw/showroom/COROLLA_SPORT'],
    [/^(crv)$/i, 'https://www.honda-taiwan.com.tw/Auto/Cars/CR-V'],
    [/^(cx5)$/i, 'https://www.mazda.com.tw/cars/mazda-cx-5'],
    [/^(gogoro)$/i, 'https://www.gogoro.com/tw'],
    [/^(gr86)$/i, 'https://www.toyota.com.tw/showroom/GR86'],
    [/^(hilux)$/i, 'https://www.toyota.com.tw/showroom/HILUX'],
    [/^(hrv)$/i, 'https://www.honda-taiwan.com.tw/Auto/Cars/HR-V'],
    [/^(hs)$/i, 'https://www.mgmotor.com.tw/configuration/hs.html'],
    [/^(hyundai)$/i, 'https://www.hyundai-motor.com.tw'],
    [/^(kicks)$/i, 'https://new.nissan.com.tw/nissan/cars/kicks'],
    [/^(kuga)$/i, 'https://www.ford.com.tw/suvs/kuga/the-all-new-kuga'],
    [/^(lbx)$/i, 'https://www.lexus.com.tw/showroom/LBX'],
    [/^(lexus)$/i, 'https://www.lexus.com.tw'],
    [/^(mg)$/i, 'https://www.mgmotor.com.tw'],
    [/^(nismo)$/i, 'https://www.nismo.co.jp/en/'],
    [/^(outlander)$/i, 'https://www.mitsubishi-motors.com.tw/outlander'],
    [/^(prado)$/i, 'https://www.toyota.com.tw/showroom/PRADO'],
    [/^(prius)$/i, 'https://www.toyota.com.tw/showroom/PRIUS_PHEV'],
    [/^(rav4)$/i, 'https://www.toyota.com.tw/showroom/RAV4'],
    [/^(rx)$/i, 'https://www.lexus.com.tw/showroom/RX'],
    [/^(rx|450e)$/i, 'https://www.lexus.com.tw/showroom/RZ%20450e'],
    [/^(sienta)$/i, 'https://www.toyota.com.tw/showroom/SIENTA'],
    [/^(tiguan)$/i, 'https://www.volkswagen.com.tw/zh/models/tiguan.html'],
    [/^(ucar)$/i, 'https://www.u-car.com.tw'],
    [/^(vios)$/i, 'https://www.toyota.com.tw/showroom/VIOS/'],
    [/^(viva)$/i, 'https://www.gogoro.com/tw/smartscooter/viva'],
    [/^(x5)$/i, 'https://www.bmw.com.tw/zh/all-models/x-series/x5/2023/highlights.html'],
    [/^(xc40)$/i, 'https://www.volvocars.com/tw/cars/xc40'],
    [/^(xc60)$/i, 'https://www.volvocars.com/tw/cars/xc60'],
    [/^(yaris)$/i, 'https://www.toyota.com.tw/showroom/YARISCROSS/'],
    [/^(zs)$/i, 'https://www.mgmotor.com.tw/configuration/zs.html'],
    [/雙龍/i, 'https://www.ssangyong.tw/'],
  ]

  const REHOUSE = [
    [['租屋', '比價'], 'https://rent.houseprice.tw'],
    [['群義', '房屋'], 'https://www.chyi.com.tw'],
    [['mix', 'rent'], 'https://tw.mixrent.com'],
    [[/不動產|房屋/i, '大家'], 'https://www.great-home.com.tw'],
    [[/不動產|房屋/i, '大師'], 'https://master1995.com.tw'],
    [[/不動產|房屋/i, '中信'], 'https://www.cthouse.com.tw'],
    [[/不動產|房屋/i, '太平洋'], 'https://www.pacific.com.tw'],
    [[/不動產|房屋/i, '世紀'], 'https://new.century21.com.tw'],
    [[/不動產|房屋/i, '台灣'], 'https://www.twhg.com.tw'],
    [[/不動產|房屋/i, '永春'], 'https://www.yes319.com/'],
    [[/不動產|房屋/i, '全國'], 'https://www.nra.com.tw'],
    [[/不動產|房屋/i, '東森'], 'https://www.etwarm.com.tw'],
    [[/不動產|房屋/i, '信義'], 'https://www.sinyi.com.tw'],
    [[/不動產|房屋/i, '蘋果'], 'https://www.applerehouse.com.tw'],
    [/^(5168)$/i, 'https://www.houseprice.tw'],
    [/^(591)$/i, 'https://www.591.com.tw'],
    [/^(台慶)$/i, 'https://buy.taiching.com.tw'],
    [/^(永義)$/i, 'https://buy.yungyi-house.com.tw'],
    [/^(永慶)$/i, 'https://www.yungching.com.tw'],
    [/^(好房網)$/i, 'https://rent.housefun.com.tw'],
    [/^(有巢氏)$/i, 'https://www.u-trust.com.tw/'],
    [/^(住商)$/i, 'https://www.hbhousing.com.tw'],
    [/^(幸福家)$/i, 'https://singfujia.com'],
    [/^(南北)$/i, 'https://snhouse.com.tw'],
    [/^(租租通)$/i, 'https://www.dd-room.com'],
    [/^(崔媽媽租屋)$/i, 'https://rent.tmm.org.tw'],
    [/^(慧雙)$/i, 'https://www.hshouse.com.tw'],
    [/^(樂居)$/i, 'https://www.leju.com.tw'],
    [/^(樂屋網)$/i, 'https://www.rakuya.com.tw'],
  ]

  const TECH = [
    [['ace', 'pro'], 'https://www.insta360.com/hk/product/insta360-ace-pro'],
    [['android', 'tv'], 'https://www.android.com/tv'],
    [['asus', 'router'], 'https://www.asus.com/tw/networking-iot-servers/wifi-routers/all-series/'],
    [['bosch', '洗碗機'], 'https://www.bosch-home.com.tw/products/dishwashers'],
    [['flip', '5'], 'https://www.samsung.com/tw/smartphones/galaxy-z-flip5/'],
    [['fold', '5'], 'https://www.samsung.com/tw/smartphones/galaxy-z-fold5/'],
    [['one', 'rs'], 'https://www.insta360.com/hk/product/insta360-oners'],
    [['one', 'ui'], 'https://www.samsung.com/tw/one-ui/'],
    [['rtx', '3060'], ''],
    [['s23', 'fe'], 'https://www.samsung.com/tw/smartphones/galaxy-s/galaxy-s23-fe-mint-128gb-sm-s7110lgdbri/'],
    [['s23', 'ultra'], 'https://www.samsung.com/tw/smartphones/galaxy-s23-ultra/'],
    [['sony', '耳機'], 'https://store.sony.com.tw/category/list/headphone-all'],
    [['sony', '相機'], 'https://store.sony.com.tw/category/list/ilc'],
    [['tp', 'link'], 'https://www.tp-link.com/tw/'],
    [['ultimate', 'ears'], 'https://www.ultimateears.com/zh-tw'],
    [[/三星|samsung/i, 'care'], 'https://www.samsung.com/tw/offer/samsung-care-plus/'],
    [[/三星|samsung/i, /手機|phone|mobile/], 'https://www.samsung.com/tw/smartphones/'],
    [[/三星|samsung/i, /平板|tab/], 'https://www.samsung.com/tw/tablets/'],
    [[/三星|samsung/i, /保固/], 'https://www.samsung.com/tw/support/warranty/'],
    [[/三星|samsung/i, /商城|shop/], 'https://www.samsung.com/tw/apps/samsung-shop-app/'],
    [[/三星|samsung/i, /電視|tv/], 'https://www.samsung.com/tw/tvs/all-tvs/'],
    [[/三星|samsung|tab/i, 's9'], 'https://www.samsung.com/tw/tablets/galaxy-tab-s9/buy/'],
    [[/firefox|mozilla/i, 'relay'], 'https://relay.firefox.com'],
    [[/status|狀態|down|service/i, /fb|facebook|meta|臉書/i], 'https://metastatus.com/'],
    [[/status|狀態|down|service/i, /github/i], 'https://www.githubstatus.com/'],
    [[/status|狀態|down|service/i, /google cloud/i], 'https://status.cloud.google.com/'],
    [[/status|狀態|down|service/i, /google|谷歌/i], 'https://www.google.com/appsstatus/dashboard/'],
    [[/status|狀態|down|service/i, /gpt|openai/i], 'https://status.openai.com/'],
    [[/status|狀態|down|service/i, /jira|atlassian/i], 'https://status.atlassian.com/'],
    [[/status|狀態|down|service/i, /notion/i], 'https://status.notion.so/'],
    [[/status|狀態|down|service/i, /sony|索尼|psn/i], 'https://status.playstation.com/zh-hant-tw/'],
    [[/status|狀態|down|service/i, /trello/i], 'https://trello.status.atlassian.com/'],
    [[/status|狀態|down|service/i, /twitter|x/i], 'https://api.twitterstat.us/'],
    [[/status|狀態|down|service|health/i, /阿里雲/i], 'https://status.aliyun.com/'],
    [[/status|狀態|down|service|health/i, /aws|amazon/i], 'https://health.aws.amazon.com/health/status'],
    [[/status|狀態|down|service|health/i, /cloudways/i], 'https://status.cloudways.com/'],
    [[/status|狀態|down|service|health/i, /digitalocean/i], 'https://status.digitalocean.com/'],
    [[/status|狀態|down|service|health/i, /hostinger/i], 'https://statuspage.hostinger.com/'],
    [[/status|狀態|down|service|health/i, /linode/i], 'https://status.linode.com/'],
    [[/status|狀態|down|service|health/i, /netflix/i], 'https://help.netflix.com/zh-tw/is-netflix-down'],
    [[/status|狀態|down|service|health/i, /netlify/i], 'https://www.netlifystatus.com/'],
    [[/status|狀態|down|service|health/i, /oracle|ocl/i], 'https://ocistatus.oraclecloud.com/#/'],
    [[/status|狀態|down|service|health/i, /ovhcloud/i], 'https://www.status-ovhcloud.com/'],
    [[/status|狀態|down|service|health/i, /vercel/i], 'https://www.vercel-status.com/'],
    [[/status|狀態|down|service|health/i, /vultr/i], 'https://status.vultr.com/'],
    [/^(1050|1060|1070|1080)$/i, 'https://www.nvidia.com/zh-tw/geforce/10-series/'],
    [/^(1630|1650|1660)$/i, 'https://www.nvidia.com/zh-tw/geforce/graphics-cards/16-series/'],
    [/^(2060|2070|2080)$/i, 'https://www.nvidia.com/zh-tw/geforce/20-series/'],
    [/^(3050|3060|3070|3080|3090)$/i, 'https://www.nvidia.com/zh-tw/geforce/graphics-cards/30-series/'],
    [/^(4050|4060|4070|4080|4090)$/i, 'https://www.nvidia.com/zh-tw/geforce/graphics-cards/40-series/'],
    [/^(十銓|十銓科技|teamgroup)$/i, 'https://www.teamgroupinc.com/tw/'],
    [/^(大通)$/i, 'https://www.px.com.tw/zh-tw'],
    [/^(大疆|dji)$/i, 'https://www.dji.com/'],
    [/^(工研院|itri)$/i, 'https://www.itri.org.tw/'],
    [/^(中國移動)$/i, 'https://www.10086.cn/index/he'],
    [/^(中國鋼鐵|中鋼|csc)$/i, 'https://www.csc.com.tw'],
    [/^(友達|auo)$/i, 'https://www.auo.com/zh-TW'],
    [/^(台灣水泥|台泥)$/i, 'https://www.taiwancement.com/tw'],
    [/^(尼康|nikon)$/i, 'https://www.nikon.com'],
    [/^(石頭科技|roborock)$/i, 'https://www.roborocktw.com'],
    [/^(任天堂|nintendo)$/i, 'https://www.nintendo.tw/'],
    [/^(光寶|光寶科技)$/, 'https://www.liteon.com/zh-tw'],
    [/^(宇瞻|宇瞻科技|apacer)$/i, 'https://www.apacer.com/zh-TW'],
    [/^(百度|baidu)$/i, 'https://www.baidu.com/'],
    [/^(米哈遊|mihoyo)$/i, 'https://www.mihoyo.com/'],
    [/^(技嘉|gigabyte)$/, 'https://www.gigabyte.com/tw'],
    [/^(佳能|canon)$/, 'https://tw.canon'],
    [/^(和碩)$/i, 'https://www.pegatroncorp.com'],
    [/^(旺宏)$/i, 'https://www.mxic.com.tw/zh-tw/Pages/default.aspx'],
    [/^(明碁|benq)$/, 'https://www.benq.com/zh-tw/index.html'],
    [/^(東芝|TOSHIBA)$/i, 'https://www.taiwanmeizhi.com/'],
    [/^(松下|panasonic)$/, 'https://www.panasonic.com/tw'],
    [/^(欣興|欣興電子|unimicron)$/, 'https://www.unimicron.com'],
    [/^(矽統)$/i, 'https://www.sis.com.tw'],
    [/^(育碧|ubisoft|ubi)$/, 'https://www.ubisoft.com/zh-tw/'],
    [/^(金士頓|金士頓科技|kingston)$/i, 'https://www.kingston.com/tw'],
    [/^(南亞科技)$/i, 'https://www.nanya.com/tw'],
    [/^(哈蘇|hasselblad)$/, 'https://www.hasselblad.com'],
    [/^(威剛|adata)$/, 'https://www.adata.com/tw'],
    [/^(帝瓦雷|devialet)$/, 'https://www.devialet.com/zh-tw'],
    [/^(美光|crucial)$/i, 'https://www.crucial.tw/'],
    [/^(英業達|inventec)$/, 'https://www.inventec.com'],
    [/^(夏普|sharp)$/, 'https://tw.sharp'],
    [/^(索尼|sony)$/i, 'https://store.sony.com.tw'],
    [/^(高通|qualcomm)$/i, 'https://www.qualcomm.com'],
    [/^(徠卡|leica)$/, 'https://leica-camera.com/zh-Hant'],
    [/^(創見|transcend)$/i, 'https://tw.transcend-info.com/'],
    [/^(博通|avago|broadcom)$/, 'https://www.broadcom.com'],
    [/^(富士通)$/i, 'https://www.fujitsu.com/tw'],
    [/^(華邦|華邦電子|winbond)$/, 'https://www.winbond.com/hq/?__locale=zh_TW'],
    [/^(華為)$/i, 'https://consumer.huawei.com/tw'],
    [/^(華碩|asus)$/, 'https://www.asus.com/tw'],
    [/^(微星|msi)$/i, 'https://tw.msi.com'],
    [/^(愛普生|epson)$/i, 'https://www.epson.com.tw'],
    [/^(新唐)$/i, 'https://www.nuvoton.com'],
    [/^(群創|innolux)$/i, 'https://www.innolux.com'],
    [/^(群暉|synology)$/i, 'https://www.synology.com/zh-tw'],
    [/^(群聯|群聯電子|phison)$/i, 'https://www.phison.com/zh-tw/'],
    [/^(漫步者|edifier)$/, 'https://www.edifier.com.tw'],
    [/^(廣穎|廣穎電通|sp|silicon ?power)$/i, 'https://www.silicon-power.com/web/tw/'],
    [/^(樂金|lg)$/, 'https://www.lg.com/tw'],
    [/^(緯創)$/i, 'https://www.wistron.com'],
    [/^(蔡司|zeiss)$/i, 'https://www.zeiss.com.tw/corporate/home.html'],
    [/^(輝達|nvidia)$/, 'https://www.nvidia.com'],
    [/^(聯發科|mediatek)$/, 'https://www.mediatek.tw'],
    [/^(聯華電子|聯電|umc)$/, 'https://www.umc.com/zh-TW/Home/Index'],
    [/^(聯詠|novatek)$/, 'https://www.novatek.com.tw/zh-TW/Home/Index'],
    [/^(聯想|lenovo)$/, 'https://www.lenovo.com/tw/zh'],
    [/^(臉書|facebook|fb)$/i, 'https://www.facebook.com'],
    [/^(鎧俠|kioxia|東芝記憶體)$/i, 'https://tw.kioxia.com/zh-tw/top.html'],
    [/^(穩懋)$/i, 'https://www.winfoundry.com/zh-TW'],
    [/^(羅技|logi|logitech)$/, 'https://www.logitech.com/zh-tw'],
    [/^(麗臺|麗臺科技|leadtek)$/i, 'https://www.leadtek.com/cht/'],
    [/^(acer)$/i, 'https://www.acer.com/tw-zh'],
    [/^(am4)$/i, 'https://www.amd.com/zh-tw/products/processors/chipsets/am4.html'],
    [/^(am5)$/i, 'https://www.amd.com/zh-tw/products/processors/chipsets/am5.html'],
    [/^(amazon)$/i, 'https://www.amazon.com'],
    [/^(amd)$/i, 'https://www.amd.com'],
    [/^(anker)$/i, 'https://www.anker.tw'],
    [/^(asml)$/i, 'https://www.asml.com/zh-tw'],
    [/^(asustor|華芸|華芸科技|asus ?nas|drivestor)$/i, 'https://www.asustor.com/zh-tw/'],
    [/^(at&t|att)$/, 'https://www.att.com'],
    [/^(ax68)$/i, 'https://www.asus.com/tw/networking-iot-servers/wifi-routers/asus-wifi-routers/rt-ax68u/'],
    [/^(ax86)$/i, 'https://www.asus.com/tw/networking-iot-servers/wifi-routers/asus-gaming-routers/rt-ax86u/'],
    [/^(ax88)$/i, 'https://www.asus.com/tw/networking-iot-servers/wifi-routers/asus-gaming-routers/rt-ax88u/'],
    [/^(belkin)$/i, 'https://www.belkin.com'],
    [/^(blueair)$/i, 'https://www.blueair.com/tw/homepage.html'],
    [/^(bosch)$/i, 'https://www.bosch.com.tw'],
    [/^(bose)$/i, 'https://www.bose.tw/zh_tw/index.html'],
    [/^(buds2)$/i, 'https://www.samsung.com/tw/audio-sound/galaxy-buds/galaxy-buds2-black-onyx-sm-r177nztabri/'],
    [/^(cloudflare)$/i, 'https://www.cloudflare.com/zh-tw'],
    [/^(corsair)$/i, 'https://www.corsair.com/tw/zh'],
    [/^(creative)$/i, 'https://tw.creative.com'],
    [/^(csc)$/i, 'https://www.csc.com.tw'],
    [/^(dell)$/i, 'https://www.dell.com/zh-tw'],
    [/^(denon)$/i, 'https://cosmoslingo.com.tw/denon'],
    [/^(dropbox)$/i, 'https://www.dropbox.com/home'],
    [/^(dsm)$/i, 'https://www.synology.com/zh-tw/dsm'],
    [/^(elecom)$/i, 'http://www.elecom.com.tw'],
    [/^(epic)$/i, 'https://store.epicgames.com/zh-Hant/'],
    [/^(fender)$/i, 'https://www.fender.com/en/start'],
    [/^(firefox)$/i, 'https://www.mozilla.org/zh-TW/firefox/new'],
    [/^(focal)$/i, 'https://focal-jmlab.com.tw/focal-brand'],
    [/^(galaxy)$/i, 'https://www.samsung.com/tw/smartphones/'],
    [/^(garmin)$/i, 'https://www.garmin.com.tw'],
    [/^(geforce)$/i, 'https://www.nvidia.com/zh-tw/geforce/drivers'],
    [/^(genelec)$/i, 'https://www.genelec.com'],
    [/^(gopro)$/i, 'https://gopro.com/en/us'],
    [/^(harman|kardon)$/, 'https://tw.harmankardon.com'],
    [/^(hp)$/i, 'https://www.hp.com/tw-zh/home.html'],
    [/^(htc)$/i, 'https://www.htc.com/tw/'],
    [/^(hulu)$/i, 'https://www.hulu.com'],
    [/^(hyperx)$/i, 'https://row.hyperx.com/zh-tw'],
    [/^(ibm)$/i, 'https://www.ibm.com/tw-zh/products'],
    [/^(insta360)$/i, 'https://www.insta360.com/hk'],
    [/^(inzone)$/i, 'https://store.sony.com.tw/category/listAll/gaming'],
    [/^(irobot)$/i, 'https://www.irobot.com.tw'],
    [/^(jbl)$/i, 'https://www.jbl-tw.com'],
    [/^(kef)$/i, 'https://tw.kef.com'],
    [/^(kvaser)$/i, 'https://www.kvaser.com/'],
    [/^(marley)$/i, 'https://www.igogosport.com/brand-marley'],
    [/^(marshall)$/i, 'https://marshall.com'],
    [/^(messenger)$/i, 'https://www.messenger.com'],
    [/^(microchip)$/i, 'https://www.microchip.com.tw'],
    [/^(montech|telon)$/, 'https://www.telon.com.tw/tc'],
    [/^(mozilla)$/i, 'https://www.mozilla.org/zh-TW'],
    [/^(ns7)$/i, 'https://store.sony.com.tw/product/SRS-NS7'],
    [/^(nxp)$/i, 'https://www.nxp.com'],
    [/^(omron)$/i, 'https://www.omron.com.tw'],
    [/^(openai)$/i, 'https://openai.com'],
    [/^(oppo)$/i, 'https://www.oppo.com/tw'],
    [/^(paramount)$/i, 'https://www.paramount.com'],
    [/^(pcan|peak ?can)$/i, 'https://www.peak-system.com/'],
    [/^(peacock)$/i, 'https://www.peacocktv.com'],
    [/^(poco)$/i, 'https://www.mi.com/tw/phone/#poco'],
    [/^(presonus)$/i, 'https://www.presonus.com/en/start'],
    [/^(ps3)$/i, 'https://www.playstation.com/zh-hant-tw/support/hardware/ps3/'],
    [/^(ps4)$/i, 'https://www.playstation.com/zh-hant-tw/ps4'],
    [/^(ps5)$/i, 'https://www.playstation.com/zh-hant-tw/ps5'],
    [/^(psn)$/i, 'https://www.playstation.com/zh-hant-tw/playstation-network/'],
    [/^(qnap)$/i, 'https://www.qnap.com/zh-tw/'],
    [/^(quora)$/i, 'https://www.quora.com/'],
    [/^(razer)$/i, 'https://www.razer.com/tw-zh'],
    [/^(reddit)$/i, 'https://www.reddit.com'],
    [/^(s22)$/i, 'https://www.samsung.com/tw/smartphones/galaxy-s22/'],
    [/^(s23)$/i, 'https://www.samsung.com/tw/smartphones/galaxy-s23/'],
    [/^(s24)$/i, 'https://www.samsung.com/tw/smartphones/galaxy-s24/'],
    [/^(s32ds)$/i, 'https://www.nxp.com/design/design-center/software/development-software/s32-design-studio-ide:S32-DESIGN-STUDIO-IDE'],
    [/^(s32k)$/i, 'https://www.nxp.com/products/processors-and-microcontrollers/arm-processors/s32-automotive-platform:S32'],
    [/^(samsung|三星)$/i, 'https://www.samsung.com/tw'],
    [/^(spotify)$/i, 'https://open.spotify.com/search'],
    [/^(startz)$/i, 'https://www.starz.com'],
    [/^(tcl)$/i, 'https://www.tcl-shop.com.tw'],
    [/^(ti)$/i, 'https://www.ti.com'],
    [/^(twitch)$/i, 'https://www.twitch.tv'],
    [/^(twitter|推特)$/i, 'https://twitter.com'],
    [/^(u23)$/i, 'https://www.htc.com/tw/smartphones/htc-u23/'],
    [/^(ubuntu)$/i, 'https://ubuntu.com/download'],
    [/^(walkman)$/i, 'https://store.sony.com.tw/category/list/dmp'],
    [/^(warp)$/i, 'https://one.one.one.one/zh-Hant'],
    [/^(x)$/i, 'https://twitter.com'],
    [/^(xg300)$/i, 'https://www.sony.com.tw/zh/electronics/wireless-speakers/srs-xg300'],
    [/^(xperia)$/i, 'https://store.sony.com.tw/category/list/xperia'],
    [/^(xpg)$/i, 'https://www.xpg.com/TW'],
    [/^阿里雲$/, 'https://www.alibabacloud.com/tc'],
    [/^hostinger$/, 'https://www.hostinger.com/'],
    [/^linode$/, 'https://www.linode.com/'],
    [/^netlify$/, 'https://www.netlify.com/'],
    [/^ovhcloud$/, 'https://us.ovhcloud.com/'],
    [/^vercel$/, 'https://vercel.com/'],
    [/^vultr$/, 'https://www.vultr.com/'],
    [/力積/i, 'https://www.powerchip.com/zh-TW'],
    [/xm3/i, 'https://store.sony.com.tw/product/WF-1000XM3'],
    [/xm4/i, 'https://store.sony.com.tw/product/WF-1000XM4'],
    [/xm5/i, 'https://store.sony.com.tw/product/WH-1000XM5'],
  ]

  const GOOGLE = [
    [['google', 'console'], 'https://search.google.com/search-console'],
    [['google', 'nest'], 'https://store.google.com/tw/product/nest_audio'],
    [['google', 'pixel'], 'https://store.google.com/tw/category/phones'],
    [['google', 'play'], 'https://play.google.com'],
    [['google', /文件|docs/], 'https://docs.google.com/document/u/0/'],
    [['google', /日曆|cal/], 'https://calendar.google.com/calendar'],
    [['google', /地圖|map/], 'https://www.google.com.tw/maps'],
    [['google', /相簿|相片|photo/], 'https://photos.google.com'],
    [['google', /硬碟|雲端|drive/], 'https://drive.google.com/drive/home'],
    [['google', /新聞|news/], 'https://news.google.com/home?hl=zh-TW&gl=TW'],
    [['google', /會議|meet/], 'https://meet.google.com/'],
    [['google', /試算表|sheet/], 'https://docs.google.com/spreadsheets/u/0/'],
    [['google', /播客|podcast/], 'https://podcasts.google.com'],
    [['google', /簡報|ppt/], 'https://docs.google.com/presentation/u/0/'],
    [['google', /dev/], 'https://developers.google.com/'],
    [['page', 'insight'], 'https://pagespeed.web.dev/'],
    [['pixel', '7'], 'https://store.google.com/tw/config/pixel_7'],
    [['pixel', '8'], 'https://store.google.com/tw/product/pixel_8'],
    [['pixel', 'buds'], 'https://store.google.com/tw/product/pixel_buds_pro'],
    [['pixel', 'pro'], 'https://store.google.com/tw/product/pixel_8_pro'],
    [['pixel', 'watch'], 'https://store.google.com/tw/product/pixel_watch_2'],
    [['web', 'dev'], 'https://web.dev/'],
    [[/android/i, /dev/], 'https://developer.android.com/'],
    [[/chrome/i, /去廣告/], 'https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm'],
    [/^(我的地圖)$/i, 'https://www.google.com/mymaps'],
    [/^(翻譯)$/i, 'https://translate.google.com.tw/?hl=zh-TW'],
    [/^(adblock)$/i, 'https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom'],
    [/^(android ?studio)$/i, 'https://developer.android.com/studio'],
    [/^(chrome)$/i, 'https://chromeenterprise.google/intl/zh_tw/browser/download'],
    [/^(chromecast|google ?tv)$/i, 'https://store.google.com/tw/product/chromecast_google_tv'],
    [/^(gmail)$/i, 'https://mail.google.com/mail'],
    [/^(keep)$/i, 'https://keep.google.com'],
    [/^(pagespeed)$/, 'https://pagespeed.web.dev/'],
    [/^(ublock)$/i, 'https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm'],
  ]
  const INTEL = [
    [[/(intel|英特爾)/i, /13/i], 'https://www.intel.com.tw/content/www/tw/zh/products/docs/processors/core/13th-gen-core-mobile-brief.html'],
    [[/(intel|英特爾)/i, /14/i], 'https://www.intel.com.tw/content/www/tw/zh/products/docs/processors/core/core-14th-gen-desktop-brief.html'],
    [[/(intel|英特爾)/i, /保固/i], 'https://supporttickets.intel.com/s/warrantyinfo?language=zh_TW'],
    [[/(intel|英特爾)/i, /arc/i], 'https://www.intel.com.tw/content/www/tw/zh/products/details/discrete-gpus/arc/arc-a-series/products.html'],
    [[/(intel|英特爾)/i, /core/i], 'https://www.intel.com.tw/content/www/tw/zh/products/details/processors/core.html'],
    [[/(intel|英特爾)/i, /driver/i], 'https://www.intel.com.tw/content/www/tw/zh/download-center/home.html'],
    [[/(intel|英特爾)/i, /evo/i], 'https://www.intel.com.tw/content/www/tw/zh/products/systems-devices/laptops/evo.html'],
    [[/(intel|英特爾)/i, /gpu/i], 'https://www.intel.com.tw/content/www/tw/zh/products/details/discrete-gpus.html'],
    [[/(intel|英特爾)/i, /wifi6/i], 'https://www.intel.com.tw/content/www/tw/zh/products/details/wireless/wi-fi-6-series.html'],
    [[/(intel|英特爾)/i, /wifi7/i], 'https://www.intel.com.tw/content/www/tw/zh/products/details/wireless/wi-fi-7-series/products.html'],
    [/^(12100)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/134584/intel-core-i312100-processor-12m-cache-up-to-4-30-ghz/specifications.html'],
    [/^(12300)$/i, 'https://ark.intel.com/content/www/tw/zh/ark/products/223095/intel-core-i3-12300-processor-12m-cache-up-to-4-40-ghz.html'],
    [/^(12500)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/96144/intel-core-i512500-processor-18m-cache-up-to-4-60-ghz/specifications.html'],
    [/^(12600)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/96149/intel-core-i512600-processor-18m-cache-up-to-4-80-ghz/specifications.html'],
    [/^(12700)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/134591/intel-core-i712700-processor-25m-cache-up-to-4-90-ghz/specifications.html'],
    [/^(12900)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/134597/intel-core-i912900-processor-30m-cache-up-to-5-10-ghz/specifications.html'],
    [/^(13400)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/230495/intel-core-i513400-processor-20m-cache-up-to-4-60-ghz/specifications.html'],
    [/^(13500)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/230580/intel-core-i513500-processor-24m-cache-up-to-4-80-ghz/specifications.html'],
    [/^(13600)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/230574/intel-core-i513600-processor-24m-cache-up-to-5-00-ghz/specifications.html'],
    [/^(13700)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/230490/intel-core-i713700-processor-30m-cache-up-to-5-20-ghz/specifications.html'],
    [/^(13900)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/230496/intel-core-i913900k-processor-36m-cache-up-to-5-80-ghz/specifications.html'],
    [/^(14600)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/236799/intel-core-i5-processor-14600k-24m-cache-up-to-5-30-ghz/specifications.html'],
    [/^(14700)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/236781/intel-core-i7-processor-14700-33m-cache-up-to-5-40-ghz/specifications.html'],
    [/^(14900)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/236773/intel-core-i9-processor-14900k-36m-cache-up-to-6-00-ghz/specifications.html'],
    [/^(6500)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/88184/intel-core-i56500-processor-6m-cache-up-to-3-60-ghz/specifications.html'],
    [/^(7700)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/97128/intel-core-i77700-processor-8m-cache-up-to-4-20-ghz/specifications.html'],
    [/^(a310)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/227958/intel-arc-a310-graphics/specifications.html'],
    [/^(a580)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/227961/intel-arc-a580-graphics/specifications.html'],
    [/^(a60m)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/232778/intel-arc-pro-a60m-graphics/specifications.html'],
    [/^(a750)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/227954/intel-arc-a750-graphics/specifications.html'],
    [/^(a770)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/229151/intel-arc-a770-graphics-16gb/specifications.html'],
    [/^(ax101)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/203014/intel-wifi-6-ax101/specifications.html'],
    [/^(ax1650)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/211610/intel-killer-wifi-6-ax1650-is/specifications.html'],
    [/^(ax1675)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/211486/intel-killer-wifi-6e-ax1675-is/specifications.html'],
    [/^(ax1690)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/217241/intel-killer-wifi-6e-ax1690-is/specifications.html'],
    [/^(ax200)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/189347/intel-wifi-6-ax200-gig/specifications.html'],
    [/^(ax201)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/130293/intel-wifi-6-ax201-gig/specifications.html'],
    [/^(ax203)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/229220/intel-wifi-6-ax203/specifications.html'],
    [/^(ax210)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/204836/intel-wifi-6e-ax210-gig/specifications.html'],
    [/^(ax211)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/204837/intel-wifi-6e-ax211-gig/specifications.html'],
    [/^(ax411)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/217242/intel-wifi-6e-ax411-gig/specifications.html'],
    [/^(be1750)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/230084/intel-killer-wifi-7-be1750-xw/specifications.html'],
    [/^(be200)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/230078/intel-wifi-7-be200/specifications.html'],
    [/^(be202)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/sku/234444/intel-wifi-7-be202/specifications.html'],
    [/^(geti)$/i, 'https://geti.intel.com/'],
    [/^(i3)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/details/processors/core/i3.html'],
    [/^(i5)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/details/processors/core/i5.html'],
    [/^(i7)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/details/processors/core/i7.html'],
    [/^(i9)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/details/processors/core/i9.html'],
    [/^(intel|英特爾)$/i, 'https://www.intel.com.tw'],
    [/^(vpro)$/i, 'https://www.intel.com.tw/content/www/tw/zh/architecture-and-technology/vpro/overview.html'],
    [/^(xeon)$/i, 'https://www.intel.com.tw/content/www/tw/zh/products/details/processors/xeon.html'],
  ]

  const MICROSOFT = [
    [['Windows', '10'], 'https://www.microsoft.com/zh-tw/software-download/windows10'],
    [['Windows', '11'], 'https://www.microsoft.com/zh-tw/software-download/windows11'],
    [['Windows', '7'], 'https://support.microsoft.com/zh-tw/windows/windows-7-%E7%B3%BB%E7%B5%B1%E9%9C%80%E6%B1%82-df0900f2-3513-a851-13e7-0d50bc24e15f'],
    [[/ie/i, /edge/i], 'https://support.microsoft.com/zh-tw/microsoft-edge/microsoft-edge-%E4%B8%AD%E7%9A%84-internet-explorer-%E6%A8%A1%E5%BC%8F-6604162f-e38a-48b2-acd2-682dbac6f0de'],
    [[/ms|microsoft/i, /drive/i], 'https://onedrive.live.com/?gologin=1'],
    [[/ms|microsoft|微軟/i, /ads|廣告/i], 'https://ads.microsoft.com/'],
    [[/ms|microsoft|微軟/i, /ai/i], 'https://www.microsoft.com/zh-tw/ai/'],
    [[/ms|microsoft|微軟/i, /defender|防毒/i], 'https://learn.microsoft.com/zh-tw/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows'],
    [[/ms|microsoft|微軟/i, /dev|開發/i], 'https://developer.microsoft.com/zh-tw/'],
    [[/ms|microsoft|微軟/i, /device|裝置/i], 'https://account.microsoft.com/devices'],
    [[/ms|microsoft|微軟/i, /edu|教育/i], 'https://www.microsoft.com/zh-tw/education/products/office'],
    [[/ms|microsoft|微軟/i, /family|家庭/i], 'https://www.microsoft.com/zh-tw/microsoft-365/family-safety'],
    [[/ms|microsoft|微軟/i, /forms|表單|問卷|投票|測驗/i], 'https://forms.office.com/'],
    [[/ms|microsoft|微軟/i, /github/i], 'https://github.com/microsoft'],
    [[/ms|microsoft|微軟/i, /help|支援|幫助|協助/i], 'https://support.microsoft.com/zh-tw'],
    [[/ms|microsoft|微軟/i, /list/i], 'https://www.microsoft.com/zh-tw/microsoft-365/microsoft-lists'],
    [[/ms|microsoft|微軟/i, /loop/i], 'https://loop.microsoft.com/'],
    [[/ms|microsoft|微軟/i, /planner|tasks/i], 'https://tasks.office.com/'],
    [[/ms|microsoft|微軟/i, /stream/i], 'https://www.microsoft365.com/launch/stream'],
    [[/ms|microsoft|微軟/i, /sway/i], 'https://support.microsoft.com/zh-tw/office/sway-%E5%BF%AB%E9%80%9F%E5%85%A5%E9%96%80-2076c468-63f4-4a89-ae5f-424796714a8a'],
    [[/ms|microsoft|微軟/i, /teams|會議|開會/i], 'https://teams.live.com'],
    [[/ms|microsoft|微軟/i, /todo|待辦事項/i], 'https://to-do.office.com/tasks/?app'],
    [[/ms|microsoft|微軟/i, /Visual/i, /Studio/i], 'https://visualstudio.microsoft.com/zh-hant/downloads/'],
    [[/ms|microsoft|office|word|excel|powerpoint/i, /365/i], 'https://www.office.com/'],
    [[/office|outlook/i, /fix/i], 'https://support.microsoft.com/zh-tw/office/%E4%BF%AE%E5%BE%A9-office-%E6%87%89%E7%94%A8%E7%A8%8B%E5%BC%8F-7821d4b6-7c1d-4205-aa0e-a6b40c5bb88b'],
    [[/office|windows/i, /crack/i], 'https://github.com/massgravel/Microsoft-Activation-Scripts'],
    [[/one/i, /drive/i], 'https://onedrive.live.com/?gologin=1'],
    [[/status|狀態|down|service/i, /azure/i], 'https://azure.status.microsoft/zh-tw/status'],
    [[/status|狀態|down|service/i, /ms|onedrive|skype|teams|microsoft|office/i], 'https://portal.office.com/servicestatus'],
    [[/status|狀態|down|service/i, /xbox/i], 'https://support.xbox.com/zh-TW/xbox-live-status'],
    [[/surface/i, /book/i], 'https://www.microsoft.com/zh-tw/surface/devices/surface-book-2/overview'],
    [[/surface/i, /duo/i], 'https://support.microsoft.com/zh-tw/surface-duo'],
    [[/surface/i, /go/i], 'https://www.microsoft.com/zh-tw/surface/devices/surface-go'],
    [[/surface/i, /hub/i], 'https://www.microsoft.com/zh-tw/surface/business/surface-hub-2'],
    [[/surface/i, /laptop/i], 'https://www.microsoft.com/zh-tw/surface/devices/surface-laptop'],
    [[/surface/i, /pro/i], 'https://www.microsoft.com/zh-tw/surface/devices/surface-pro/overview'],
    [[/surface/i, /studio/i], 'https://www.microsoft.com/zh-tw/surface/devices/surface-studio'],
    [/^(azure)$/i, 'https://azure.microsoft.com/zh-tw'],
    [/^(bing)$/i, 'https://www.bing.com'],
    [/^(copilot)$/i, 'https://www.microsoft.com/zh-tw/copilot'],
    [/^(edge)$/i, 'https://www.microsoft.com/zh-tw/edge/business/download'],
    [/^(excel)$/i, 'https://www.office.com/launch/Excel'],
    [/^(gamepass)$/i, 'https://www.xbox.com/zh-TW/xbox-game-pass/pc-game-pass'],
    [/^(github)$/i, 'https://github.com'],
    [/^(ie)$/i, 'https://support.microsoft.com/zh-tw/windows/internet-explorer-%E4%B8%8B%E8%BC%89-d49e1f0d-571c-9a7b-d97e-be248806ca70'],
    [/^(msn)$/i, 'https://www.msn.com/zh-tw'],
    [/^(office)$/i, 'https://www.office.com'],
    [/^(onenote)$/i, 'https://www.onenote.com'],
    [/^(outlook)$/i, 'https://outlook.live.com/mail/0/'],
    [/^(powerpoint|ppt)$/i, 'https://www.office.com/launch/PowerPoint'],
    [/^(powertoys)$/i, 'https://learn.microsoft.com/zh-tw/windows/powertoys/'],
    [/^(project)$/i, 'https://www.microsoft.com/zh-tw/microsoft-365/project/project-management-software'],
    [/^(publisher)$/i, 'https://www.microsoft.com/zh-tw/microsoft-365/publisher'],
    [/^(pwsh|powershell)$/i, 'https://github.com/PowerShell/PowerShell'],
    [/^(sharepoint)$/i, 'https://www.sharepoint.com'],
    [/^(skype)$/i, 'https://web.skype.com'],
    [/^(surface)$/i, 'https://www.microsoft.com/zh-tw/surface'],
    [/^(teams)$/i, 'https://teams.live.com'],
    [/^(visio)$/i, 'https://www.microsoft.com/zh-tw/microsoft-365/visio/flowchart-software'],
    [/^(vs(2022|2019|2017|2013|2010))$/i, 'https://learn.microsoft.com/en-us/visualstudio/windows'],
    [/^(vscode|vsc)$|(studio ?code)/i, 'https://code.visualstudio.com'],
    [/^(webview2)$/i, 'https://developer.microsoft.com/zh-tw/microsoft-edge/webview2'],
    [/^(winget)$/i, 'https://learn.microsoft.com/zh-tw/windows/package-manager/winget/'],
    [/^(word)$/i, 'https://www.office.com/launch/Word'],
    [/^(xbox)$/i, 'https://www.xbox.com/zh-TW'],
    [/net framework/i, 'https://dotnet.microsoft.com/en-us/download/dotnet-framework'],
    [/SQL ?Server/i, 'https://www.microsoft.com/zh-tw/sql-server/sql-server-downloads'],
  ]

  const AMD = [
    [['6500', 'xt'], 'https://www.amd.com/zh-hant/products/graphics/amd-radeon-rx-6500-xt'],
    [['6600', 'xt'], 'https://www.amd.com/zh-hant/products/graphics/amd-radeon-rx-6600-xt'],
    [['6650', 'xt'], 'https://www.amd.com/zh-hant/products/graphics/amd-radeon-rx-6650-xt'],
    [['6700', 'xt'], 'https://www.amd.com/zh-hant/products/graphics/amd-radeon-rx-6700-xt'],
    [['6750', 'xt'], 'https://www.amd.com/zh-hant/products/graphics/amd-radeon-rx-6750-xt'],
    [['7600', 'xt'], 'https://www.amd.com/zh-hant/products/graphics/amd-radeon-rx-7600-xt'],
    [['7700', 'xt'], 'https://www.amd.com/zh-hant/products/graphics/amd-radeon-rx-7700-xt'],
    [['7800', 'xt'], 'https://www.amd.com/zh-hant/products/graphics/amd-radeon-rx-7800-xt'],
    [['7900', 'xt'], 'https://www.amd.com/zh-hant/products/graphics/amd-radeon-rx-7900xtx'],
    [/^(6600)$/i, 'https://www.amd.com/zh-hant/products/graphics/amd-radeon-rx-6600'],
    [/^(7600)$/i, 'https://www.amd.com/zh-hant/products/apu/amd-ryzen-5-7600'],
    [/^(7600x)$/i, 'https://www.amd.com/zh-hant/products/cpu/amd-ryzen-5-7600x'],
    [/^(7700x)$/i, 'https://www.amd.com/zh-hant/products/cpu/amd-ryzen-7-7700x'],
    [/^(7950)$/i, 'https://www.amd.com/zh-hant/products/cpu/amd-ryzen-9-7950x'],
    [/^(radeon)$/i, 'https://www.amd.com/zh-hant/graphics/radeon-rx-graphics'],
    [/^(ryzen)$/i, 'https://www.amd.com/zh-hant/processors/ryzen'],
  ]

  const APPLE = [
    [['air', 'pods'], 'https://www.apple.com/tw/airpods'],
    [['car', 'play'], 'https://www.apple.com/tw/ios/carplay'],
    [['care', 'kit'], 'https://developer.apple.com/carekit'],
    [['final', 'cut'], 'https://www.apple.com/tw/final-cut-pro'],
    [['find', 'my'], 'https://www.icloud.com/find'],
    [['firmware', 'apple'], 'https://appledb.dev/firmware.html'],
    [['firmware', 'ios'], 'https://appledb.dev/firmware.html'],
    [['firmware', 'ipad'], 'https://appledb.dev/firmware.html'],
    [['firmware', 'iphone'], 'https://appledb.dev/firmware.html'],
    [['game', 'center'], 'https://support.apple.com/zh-tw/105022'],
    [['genius', 'bar'], 'https://www.apple.com/tw/retail/geniusbar'],
    [['home', 'pod'], 'https://www.apple.com/tw/homepod-2nd-generation'],
    [['icloud', /日曆|行事曆|cal/i], 'https://www.icloud.com/calendar'],
    [['icloud', /信箱|mail/i], 'https://www.icloud.com/mail'],
    [['icloud', /待辦事項|remind/i], 'https://www.icloud.com/reminders'],
    [['icloud', /筆記|備忘錄|note/i], 'https://www.icloud.com/notes'],
    [['icloud', /照片|photo/i], 'https://www.icloud.com/photos'],
    [['ipad', '維修'], 'https://support.apple.com/zh-tw/ipad/repair'],
    [['ipad', 'air'], 'https://www.apple.com/tw/ipad-air'],
    [['ipad', 'mini'], 'https://www.apple.com/tw/ipad-mini'],
    [['ipad', 'os'], 'https://www.apple.com/tw/ipados'],
    [['ipad', 'pro'], 'https://www.apple.com/tw/ipad-pro'],
    [['iphone', '12'], 'https://support.apple.com/kb/SP830?locale=zh_TW'],
    [['iphone', '13'], 'https://www.apple.com/tw/iphone-13'],
    [['iphone', '14'], 'https://www.apple.com/tw/iphone-14'],
    [['iphone', '15'], 'https://www.apple.com/tw/iphone-15'],
    [['iphone', 'se'], 'https://www.apple.com/tw/iphone-se'],
    [['iphone', /手冊|help/i], 'https://support.apple.com/zh-tw/guide/iphone/welcome/ios'],
    [['iphone', /維修|repair/i], 'https://support.apple.com/zh-tw/iphone/repair'],
    [['ipsw', 'beta'], 'https://ipswbeta.dev/'],
    [['ipsw', 'download'], 'https://appledb.dev/firmware.html'],
    [['jailbreak', 'ios'], 'https://www.reddit.com/r/jailbreak/'],
    [['jailbreak', 'iphone'], 'https://www.reddit.com/r/jailbreak/'],
    [['logic', 'pro'], 'https://www.apple.com/tw/logic-pro'],
    [['mac', 'mini'], 'https://www.apple.com/tw/mac-mini'],
    [['mac', 'os'], 'https://www.apple.com/tw/macos'],
    [['mac', 'pro'], 'https://www.apple.com/tw/mac-pro'],
    [['mac', 'studio'], 'https://www.apple.com/tw/mac-studio'],
    [['mac', /維修|repair/], 'https://support.apple.com/zh-tw/mac/repair'],
    [['mac', /購買|buy/], 'https://www.apple.com/tw/shop/buy-mac'],
    [['macbook', 'air'], 'https://www.apple.com/tw/macbook-air'],
    [['macbook', 'pro'], 'https://www.apple.com/tw/macbook-pro'],
    [['pro', 'max'], 'https://www.apple.com/tw/iphone-15-pro/'],
    [['product', 'red'], 'https://www.apple.com/tw/product-red'],
    [['safari', /瀏覽|apple|ios/], 'https://www.apple.com/tw/safari'],
    [['sideload', 'ios'], 'https://sideloadly.io/'],
    [['studio', 'display'], 'https://www.apple.com/tw/studio-display'],
    [['trade', 'in'], 'https://www.apple.com/tw/shop/trade-in'],
    [['ultra', '2'], 'https://www.apple.com/tw/apple-watch-ultra-2'],
    [['vision', 'os'], 'https://developer.apple.com/visionos/'],
    [['watch', '9'], 'https://www.apple.com/tw/apple-watch-series-9'],
    [['watch', '錶帶'], 'https://www.apple.com/tw/shop/watch/bands'],
    [['watch', 'nike'], 'https://www.apple.com/tw/apple-watch-nike'],
    [['watch', 'os'], 'https://www.apple.com/tw/watchos'],
    [['watch', 'se'], 'https://www.apple.com/tw/apple-watch-se'],
    [['xdr', 'display'], 'https://www.apple.com/tw/pro-display-xdr'],
    [[/^ipsw$/], 'https://appledb.dev/device-selection/'],
    [[/apple|蘋果/i, '支援'], 'https://support.apple.com/zh-tw'],
    [[/apple|蘋果/i, '行事曆'], 'https://www.icloud.com/calendar'],
    [[/apple|蘋果/i, '保固'], 'https://checkcoverage.apple.com/tw/zh?cid=gn-ols-checkcoverage-lp-get_help'],
    [[/apple|蘋果/i, '客服'], 'https://www.apple.com/tw/contact'],
    [[/apple|蘋果/i, '待辦事項'], 'https://www.icloud.com/reminders'],
    [[/apple|蘋果/i, '配件'], 'https://www.apple.com/tw/shop/accessories/all'],
    [[/apple|蘋果/i, '備忘錄'], 'https://www.icloud.com/notes'],
    [[/apple|蘋果/i, '維修'], 'https://support.apple.com/zh-tw/repair'],
    [[/apple|蘋果/i, '聯絡'], 'https://www.apple.com/tw/contact'],
    [[/apple|蘋果/i, '聯絡人'], 'https://www.icloud.com/contacts'],
    [[/apple|蘋果/i, 'book'], 'https://www.apple.com/tw/apple-books'],
    [[/apple|蘋果/i, 'care'], 'https://www.apple.com/tw/support/products'],
    [[/apple|蘋果/i, 'event'], 'https://www.apple.com/tw/apple-events/'],
    [[/apple|蘋果/i, 'id'], 'https://appleid.apple.com'],
    [[/apple|蘋果/i, 'mail'], 'https://www.icloud.com/mail'],
    [[/apple|蘋果/i, 'music'], 'https://music.apple.com/tw/browse'],
    [[/apple|蘋果/i, 'note'], 'https://www.icloud.com/notes'],
    [[/apple|蘋果/i, 'one'], 'https://www.apple.com/tw/apple-one'],
    [[/apple|蘋果/i, 'pay'], 'https://www.apple.com/tw/apple-pay'],
    [[/apple|蘋果/i, 'pencil'], 'https://www.apple.com/tw/apple-pencil'],
    [[/apple|蘋果/i, 'podcast'], 'https://www.apple.com/tw/apple-podcasts'],
    [[/apple|蘋果/i, 'store'], 'https://www.apple.com/tw/store'],
    [[/apple|蘋果/i, 'tv'], 'https://tv.apple.com/tw'],
    [[/apple|蘋果/i, 'tv'], 'https://www.apple.com/tw/tv-home'],
    [[/apple|蘋果/i, 'watch'], 'https://www.apple.com/tw/watch'],
    [[/apple|icloud/i, /聯絡人|contacts|通訊錄/i], 'https://www.icloud.com/contacts'],
    [[/icloud|iphone|ipad|watch/i, /尋找|find/], 'https://www.icloud.com/find'],
    [[/iphone|ios/i, 'esim'], 'https://support.apple.com/zh-tw/HT212780'],
    [[/status|狀態|down|service|系統/i, /apple/i], 'https://www.apple.com/tw/support/systemstatus'],
    [/^(9to5mac)$/i, 'https://9to5mac.com/'],
    [/^(airtag)$/i, 'https://www.apple.com/tw/airtag'],
    [/^(altstore)$/i, 'https://altstore.io/'],
    [/^(app ?store)$/i, 'https://www.apple.com/tw/app-store'],
    [/^(apple)$/i, 'https://www.apple.com/tw/store'],
    [/^(appledb)$/i, 'https://appledb.dev/device-selection/'],
    [/^(appleinsider)$/i, 'https://appleinsider.com/'],
    [/^(arcade)$/i, 'https://www.apple.com/tw/apple-arcade'],
    [/^(carplay)$/i, 'https://www.apple.com/tw/ios/carplay'],
    [/^(facetime)$/i, 'https://support.apple.com/zh-tw/105088'],
    [/^(handoff)$/i, 'https://support.apple.com/zh-tw/102426'],
    [/^(homekit)$/i, 'https://www.apple.com/tw/shop/accessories/all/homekit'],
    [/^(icloud)$/i, 'https://www.icloud.com/iclouddrive'],
    [/^(imac)$/i, 'https://www.apple.com/tw/imac'],
    [/^(imore)$/i, 'https://www.imore.com/'],
    [/^(ios)$/i, 'https://www.apple.com/tw/ios'],
    [/^(ipad)$/i, 'https://www.apple.com/tw/ipad'],
    [/^(iphone)$/i, 'https://www.apple.com/tw/iphone'],
    [/^(iwatch)$/i, 'https://www.apple.com/tw/watch'],
    [/^(iwork)$/i, 'https://www.apple.com/tw/iwork'],
    [/^(mac|macbook)$/, 'https://www.apple.com/tw/mac'],
    [/^(macos)$/i, 'https://www.apple.com/tw/macos'],
    [/^(macrumors)$/i, 'https://www.macrumors.com/'],
    [/^(macworld)$/i, 'https://www.macworld.com/'],
    [/^(magsafe)$/i, 'https://www.apple.com/tw/shop/goto/accessories/magsafe'],
    [/^(mbp)$/i, 'https://www.apple.com/tw/macbook-pro'],
    [/^(quicktime)$/i, 'https://support.apple.com/kb/dl837?locale=zh_TW'],
    [/^(sideloadly)$/i, 'https://sideloadly.io/'],
    [/^(siri)$/i, 'https://www.apple.com/tw/siri'],
    [/^(TrollStore)$/i, 'https://github.com/opa334/TrollStore'],
    [/^(wwdc)$/i, 'https://www.apple.com/tw/apple-events/'],
    [/^bridgeOS$/i, 'https://apple.fandom.com/wiki/BridgeOS/'],
    [/^ITerm$/i, 'https://iterm2.com/'],
    [/^itunes$/i, 'https://www.apple.com/tw/itunes/'],
    [/^Touch ?Bar$/i, 'https://support.apple.com/zh-tw/guide/mac-help/mchlbfd5b039/mac'],
    [/^Vision ?Pro$/i, 'https://www.apple.com/apple-vision-pro/'],
  ]

  const SOFT = [
    [['7', 'zip'], 'https://www.7-zip.org'],
    [['adobe', 'animate'], 'https://www.adobe.com/tw/products/animate.html'],
    [['adobe', 'stock'], 'https://stock.adobe.com/tw'],
    [['after', 'effects'], 'https://www.adobe.com/tw/products/aftereffects.html'],
    [['android', 'studio'], 'https://developer.android.com/studio'],
    [['auto', 'cad'], 'https://www.autodesk.com.tw/products/autocad/free-trial'],
    [['chart', /js|npm/], 'https://www.npmjs.com/package/chart.js'],
    [['clash', 'window'], 'https://github.com/topics/clash-for-windows'],
    [['creative', 'cloud'], 'https://www.adobe.com/tw/creativecloud.html'],
    [['creo', 'cad'], 'https://www.ptc.com/en/products/creo'],
    [['css', 'trick'], 'https://css-tricks.com/'],
    [['fusion', '360'], 'https://www.autodesk.com/products/fusion-360/overview'],
    [['ip', 'angry'], 'https://angryip.org/download'],
    [['ip', 'scan'], 'https://www.advanced-ip-scanner.com/tw/'],
    [['kagi', 'gpt'], 'https://kagi.com/fastgpt/'],
    [['linux', 'mint'], 'https://linuxmint.com/'],
    [['next', 'js'], 'https://nextjs.org'],
    [['node', 'js'], 'https://nodejs.org'],
    [['notepad', '++'], 'https://notepad-plus-plus.org/downloads'],
    [['pathwave', 'ads'], 'https://www.keysight.com/us/en/products/software/pathwave-design-software/pathwave-advanced-design-system.html'],
    [['serial', /js|npm/], 'https://www.npmjs.com/package/serialport'],
    [['sketch', 'up'], 'https://www.sketchup.com/zh-TW'],
    [['solid', 'edge'], 'https://solidedge.siemens.com/zh-tw'],
    [['source', 'tree'], 'https://www.sourcetreeapp.com'],
    [['tortoise', 'git'], 'https://tortoisegit.org'],
    [[/adobe|acrobat|pdf/i, 'reader'], 'https://www.adobe.com/tw/acrobat/pdf-reader.html'],
    [/^(3ds)$/i, 'https://www.3ds.com'],
    [/^(卡巴|卡巴斯基|kaspersky)$/i, 'https://www.kaspersky.com.tw/'],
    [/^(必特|bitdefender)$/i, 'https://www.bitdefender.com/'],
    [/^(有道雲(筆記)?)$/i, ''],
    [/^(原神)$/i, 'https://genshin.hoyoverse.com/zh-tw/'],
    [/^(崩壞)$/i, 'https://honkaiimpact3.hoyoverse.com/tw/zh-tw/home/'],
    [/^(諾頓|norton)$/i, 'https://tw.norton.com/'],
    [/^(趨勢|趨勢科技|trendmicro|pc-cillin)$/i, 'https://www.trendmicro.com/zh_tw/business.html'],
    [/^(abaqus)$/i, 'https://www.3ds.com/products/simulia/abaqus'],
    [/^(acrobat)$/i, 'https://www.adobe.com/tw/acrobat.html'],
    [/^(adguard ?home|adg)$/i, 'https://github.com/AdguardTeam/AdGuardHome'],
    [/^(adguard)$/i, 'https://adguard.com/zh_tw/welcome.html'],
    [/^(airtable)$/i, 'https://www.airtable.com/'],
    [/^(altair)$/i, 'https://altair.com'],
    [/^(angular)$/i, 'https://angular.tw'],
    [/^(ansys)$/i, 'https://www.ansys.com/zh-tw'],
    [/^(any ?desk)$/i, 'https://anydesk.com/zht'],
    [/^(apache)$/i, 'https://httpd.apache.org'],
    [/^(aquent)$/i, 'https://aquent.com'],
    [/^(asana)$/i, 'https://app.asana.com'],
    [/^(atlassian)$/i, 'https://www.atlassian.com'],
    [/^(autodesk)$/i, 'https://www.autodesk.com.tw'],
    [/^(avast)$/i, 'https://www.avast.com/zh-tw/index#pc'],
    [/^(avg)$/i, 'https://www.avg.com/zh-tw/homepage'],
    [/^(avira)$/i, 'https://www.avira.com/zh-tw/free-antivirus'],
    [/^(aws)$/i, 'https://aws.amazon.com/tw'],
    [/^(bandizip)$/i, 'https://tw.bandisoft.com/bandizip/'],
    [/^(bitbucket)$/i, 'https://bitbucket.org'],
    [/^(Boost ?Note)$/i, 'https://boostnote.io/'],
    [/^(bootstrap)$/i, 'https://getbootstrap.com'],
    [/^(brew|homebrew)$/, 'https://brew.sh'],
    [/^(canva)$/i, 'https://www.canva.com/zh_tw'],
    [/^(CCleaner)$/i, 'https://www.ccleaner.com/ccleaner/download'],
    [/^(ClickUp)$/i, 'https://clickup.com/'],
    [/^(cmake)$/i, 'https://cmake.org'],
    [/^(composer)$/i, 'https://getcomposer.org'],
    [/^(comsol)$/i, 'https://www.comsol.com'],
    [/^(crowdstrike)$/i, 'https://www.crowdstrike.com/zh-tw'],
    [/^(cygwin)$/i, 'https://www.cygwin.com/'],
    [/^(debian)$/i, 'https://www.debian.org/'],
    [/^(docker)$/i, 'https://www.docker.com'],
    [/^(dreamweaver)$/i, 'https://www.adobe.com/tw/products/dreamweaver.html'],
    [/^(Eclipse)$/i, 'https://www.eclipse.org/downloads/'],
    [/^(eset)$/i, 'https://www.eset.com/tw/'],
    [/^(Evernote)$/i, 'https://evernote.com/'],
    [/^(Everything|voidtools)$/i, 'https://www.voidtools.com/zh-cn/downloads/'],
    [/^(feko)$/i, 'https://altair.com/feko'],
    [/^(fiddler)$/i, 'https://www.telerik.com/fiddler'],
    [/^(figma)$/i, 'https://www.figma.com/'],
    [/^(file ?zilla)$/i, 'https://filezilla-project.org/'],
    [/^(flutter)$/i, 'https://flutter.dev'],
    [/^(freshworks)$/i, 'https://www.freshworks.com/hk'],
    [/^(Geo ?Gebra)$/i, 'https://www.geogebra.org/?lang=zh-TW'],
    [/^(git)$/i, 'https://git-scm.com'],
    [/^(gitlab)$/i, 'https://gitlab.com'],
    [/^(goodnotes)$/i, 'https://www.goodnotes.com/zh-hk'],
    [/^(hfss)$/i, 'https://www.ansys.com/zh-tw/products/electronics/ansys-hfss'],
    [/^(honey ?view)$/i, 'https://tw.bandisoft.com/honeyview/'],
    [/^(iA ?Writer)$/i, 'https://ia.net/writer/zh-hant'],
    [/^(illustrator)$/i, 'https://www.adobe.com/tw/products/illustrator.html'],
    [/^(incopy)$/i, 'https://www.adobe.com/tw/products/incopy.html'],
    [/^(indesign)$/i, 'https://www.adobe.com/tw/products/indesign.html'],
    [/^(jenkins)$/i, 'https://www.jenkins.io'],
    [/^(jetbrains|IntelliJ( ?IDEA)?)$/i, 'https://www.jetbrains.com/idea/'],
    [/^(jira)$/i, 'https://www.atlassian.com/zh/software/jira'],
    [/^(joplin)$/i, 'https://joplinapp.org/'],
    [/^(jquery)$/i, 'https://jquery.com'],
    [/^(kagi)$/i, 'https://kagi.com/'],
    [/^(kali)$/i, 'https://www.kali.org/'],
    [/^(lightroom)$/i, 'https://www.adobe.com/tw/products/photoshop-lightroom.html'],
    [/^(Listary)$/i, 'https://www.listary.com/'],
    [/^(Math ?Cad)$/i, 'https://www.mathcad.com/tw'],
    [/^(math ?type|wiris)$/i, 'https://www.wiris.com/en/mathtype/'],
    [/^(MATLAB|mathworks)$/i, 'https://www.mathworks.com/products/matlab.html'],
    [/^(MEmu)$/i, 'https://www.memuplay.com/'],
    [/^(minecraft)$/i, 'https://www.minecraft.net/zh-hant'],
    [/^(Mini ?tab)$/i, 'https://www.minitab.com/'],
    [/^(miro)$/i, 'https://miro.com/'],
    [/^(mongodb)$/i, 'https://www.mongodb.com'],
    [/^(nextdns)$/i, 'https://nextdns.io/zht'],
    [/^(notability)$/i, 'https://notability.com/'],
    [/^(nox)$/i, 'https://tw.bignox.com/'],
    [/^(Obsidian)$/i, 'https://obsidian.md/'],
    [/^(okta)$/i, 'https://www.okta.com'],
    [/^(open ?vpn)$/i, 'https://openvpn.net/'],
    [/^(origin)$/i, 'https://www.ea.com/zh-tw/games/library/pc-download'],
    [/^(Pandoc)$/i, 'https://pandoc.org/'],
    [/^(peazip)$/i, 'https://peazip.github.io/'],
    [/^(photoshop)$/i, 'https://www.adobe.com/tw/products/photoshop.html'],
    [/^(Pic ?Pick)$/i, 'https://picpick.app/zh-tw/'],
    [/^(postman)$/i, 'https://www.postman.com'],
    [/^(Pot ?Player)$/i, 'https://potplayer.daum.net/?lang=zh_TW'],
    [/^(premiere)$/i, 'https://www.adobe.com/tw/products/premiere.html'],
    [/^(ptc)$/i, 'https://www.ptc.com/tw'],
    [/^(PuTTY)$/i, 'https://putty.org/'],
    [/^(python)$/i, 'https://www.python.org'],
    [/^(qB.*?torrent)$/i, 'https://www.qbittorrent.org/download'],
    [/^(react)$/i, 'https://react.dev'],
    [/^(regexper)$|regex.*?visual/i, 'https://regexper.com/'],
    [/^(remcom)$/i, 'https://www.remcom.com'],
    [/^(Revo ?Uninstaller)$/i, 'https://www.revouninstaller.com/'],
    [/^(sakura ?editor)$/i, 'https://sakura-editor.github.io/'],
    [/^(Secure ?CRT)$/i, 'https://www.vandyke.com/products/securecrt/'],
    [/^(share ?x)$/i, 'https://getsharex.com/'],
    [/^(siemens)$/i, 'https://www.siemens.com/tw/zh.html'],
    [/^(Simplenote)$/i, 'https://simplenote.com/'],
    [/^(simscale)$/i, 'https://www.simscale.com'],
    [/^(Slack)$/i, 'https://slack.com/intl/zh-tw'],
    [/^(solidworks)$/i, 'https://www.solidworks.com'],
    [/^(Space ?Sniffer)$/i, 'http://www.uderzo.it/main_products/space_sniffer/download.html'],
    [/^(spaceclaim)$/i, 'https://www.ansys.com/zh-tw/products/3d-design/ansys-spaceclaim'],
    [/^(splunk)$/i, 'https://www.splunk.com/zh_tw'],
    [/^(SPSS)$/i, 'https://www.ibm.com/spss'],
    [/^(sublime)$/i, 'https://www.sublimetext.com'],
    [/^(Sublime|Sublime ?text)$/i, 'https://www.sublimetext.com/'],
    [/^(subversion|svn)$/, 'https://tortoisesvn.net/downloads.zh.html'],
    [/^(Symbolab)$/i, 'https://www.symbolab.com/'],
    [/^(tailscale)$/i, 'https://tailscale.com'],
    [/^(tailwind)$/i, 'https://tailwindcss.com'],
    [/^(Team ?Viewer)$/i, 'https://www.teamviewer.com/tw/'],
    [/^(telegram)$/i, 'https://telegram.org'],
    [/^(tera ?term)$/i, 'https://github.com/TeraTermProject/teraterm/releases'],
    [/^(tinypng)$/i, 'https://tinypng.com'],
    [/^(Todoist)$/i, 'https://todoist.com/zh-TW'],
    [/^(tomsguide)$/i, 'https://www.tomsguide.com/'],
    [/^(Tree ?Size)$/i, 'https://www.jam-software.com/treesize_free'],
    [/^(trello)$/i, 'https://trello.com'],
    [/^(twilio)$/i, 'https://www.twilio.com/en-us'],
    [/^(typora)$/i, 'https://typora.io/'],
    [/^(ulysses)$/i, 'https://ulysses.app/'],
    [/^(VirtualBox)$/i, 'https://www.virtualbox.org/'],
    [/^(vite)$/i, 'https://cn.vitejs.dev'],
    [/^(vue|vuejs)$/, 'https://vuejs.org'],
    [/^(w3s)$/i, 'https://www.w3schools.com/'],
    [/^(win ?compose)$/i, 'https://github.com/samhocevar/wincompose'],
    [/^(Win ?Merge)$/i, 'https://winmerge.org/downloads/?lang=zh_tw'],
    [/^(WinDirStat)$/i, 'https://windirstat.net/'],
    [/^(Winplot)$/i, 'https://math.hawaii.edu/wordpress/winplot/'],
    [/^(WinSCP)$/i, 'https://winscp.net/eng/index.php'],
    [/^(wintun)$/i, 'https://www.wintun.net/'],
    [/^(winzip)$/i, 'https://www.winzip.com/'],
    [/^(wireguard)$/i, 'https://www.wireguard.com/'],
    [/^(Wireshark)$/i, 'https://www.wireshark.org/download.html'],
    [/^(Wolfram|mathematica)$/i, 'https://www.wolfram.com/mathematica/'],
    [/^(workday)$/i, 'https://www.workday.com'],
    [/^(xda)$/i, 'https://www.xda-developers.com'],
    [/^(xmind)$/i, 'https://xmind.app/'],
    [/^(xming)$/i, 'https://sourceforge.net/projects/xming/'],
    [/^(zendesk)$/i, 'https://www.zendesk.tw'],
    [/^(zerotier)$/i, 'https://www.zerotier.com'],
    [/^(zoom)$/i, 'https://zoom.us/zh-tw/signin'],
    [/^android$/i, 'https://www.android.com/intl/zh-TW_tw'],
    [/^Blender$/i, 'https://www.blender.org/'],
    [/^codeblocks$/i, 'https://www.codeblocks.org/'],
    [/^Godot$/i, 'https://godotengine.org/'],
    [/^MariaDB$/i, 'https://mariadb.org/'],
    [/^MySQL$/i, 'https://www.mysql.com/'],
    [/^PyCharm$/i, 'https://www.jetbrains.com/pycharm/'],
    [/^Q.?Dir$/i, 'https://www.softwareok.com/?Download=Q-Dir'],
    [/^Unity$/i, 'https://unity.com/'],
    [/^unreal ?engine|虛幻引擎$/i, 'https://www.unrealengine.com/zh-CN/'],
    [/^vlc$/i, 'https://www.videolan.org/vlc/index.zh_TW.html'],
    // [/^()$/i, ''],
    // [/^()$/i, ''],
  ]

  const KEYWORDS = [
    ...AMD,
    ...APPLE,
    ...BANKS,
    ...CURE,
    ...GOOGLE,
    ...GOV,
    ...INTEL,
    ...MICROSOFT,
    ...MOTOR,
    ...PLACE,
    ...REHOUSE,
    ...SCHOOL,
    ...SOFT,
    ...STOCK,
    ...TECH,
    ...TRAVEL,
    // [/^()$/i, ''],
    [['三商', '巧福'], 'https://www.3375.com.tw'],
    [['三商', '投控'], 'https://www.mercuries.com.tw'],
    [['三菱', '電機'], 'https://tw.mitsubishielectric.com/zh'],
    [['大樹', '藥局'], 'https://www.greattree.com.tw'],
    [['包裹', '郵'], 'https://www.post.gov.tw/post/internet/SearchZone/index.jsp?ID=1396157311807'],
    [['包裹', /宅急便|黑貓/], 'https://www.t-cat.com.tw/inquire/trace.aspx'],
    [['地址', /英文|中翻|英譯|翻譯/], 'https://twzipcode.com'],
    [['店到店', 'ok'], 'https://ecservice.okmart.com.tw/Tracking/Search'],
    [['東森', '新聞'], 'https://www.youtube.com/watch?v=2dfAzcDf8Zg'],
    [['東森', '購物'], 'https://www.etmall.com.tw'],
    [['東森', '寵物'], 'https://www.etipets.com'],
    [['肯德基', '優惠'], 'https://kfc.izo.tw'],
    [['阿瘦', '皮鞋'], 'https://www.aso.com.tw'],
    [['高鐵', '台灣'], 'https://www.thsrc.com.tw'],
    [['捷運', '台中'], 'https://www.tmrt.com.tw'],
    [['捷運', '台北'], 'https://www.metro.taipei'],
    [['捷運', '時刻'], 'https://www.metro.taipei/cp.aspx?n=91974F2B13D997F1'],
    [['捷運', '桃園'], 'https://www.tymetro.com.tw/tymetro-new/tw/index.php'],
    [['捷運', '高雄'], 'https://www.krtc.com.tw'],
    [['捷運', '新北'], 'https://www.ntmetro.com.tw'],
    [['捷運', '機場'], 'https://www.tymetro.com.tw/tymetro-new/tw/index.php'],
    [['統一', '甜甜圈'], 'https://www.misterdonut.com.tw'],
    [['遠傳', '電收'], 'https://www.fetc.net.tw'],
    [['價格', 'com'], 'https://kakaku.com'],
    [['bb', '寬頻'], 'https://www.homeplus.net.tw/cable'],
    [['cake', 'resume'], 'https://www.cakeresume.com/zh-TW'],
    [['express', 'js'], 'https://expressjs.com/zh-tw'],
    [['garmin', '導航'], 'https://www.garmin.com.tw/products/ontheroad'],
    [['grease', 'fork'], 'https://greasyfork.org/zh-TW'],
    [['home', /plus|\+/], 'https://www.homeplus.net.tw/cable'],
    [['ssl', 'test'], 'https://www.ssllabs.com/ssltest/'],
    [['ti', 'dev'], 'https://dev.ti.com/tirex/explore'],
    [['uber', 'eat'], 'https://www.ubereats.com/tw'],
    [[/711|小7|統一超商|seven/i, '包裹'], 'https://eservice.7-11.com.tw/e-tracking/search.aspx'],
    [[/711|小7|統一超商|seven/i, '店到店'], 'https://myship.7-11.com.tw'],
    [[/711|小7|統一超商|seven/i, /門市|map|店舖/], 'https://emap.pcsc.com.tw/'],
    [[/711|小7|統一超商|seven/i, /雲端|列印/], 'https://print.ibon.com.tw/ibonprinter'],
    [[/台鐵|火車/i, '時刻表'], 'https://tw.piliapp.com/tw-railway'],
    [[/巨匠/i, /語/i], 'https://www.soeasyedu.com.tw/'],
    [[/全家|fami/i, '店到店'], 'https://fmec.famiport.com.tw'],
    [[/全家|fami/i, /門市|map|店舖/i], 'https://www.family.com.tw/Marketing/Map'],
    [[/全家|fami/i, /雲端|列印/], 'https://www.famiport.com.tw/Web_Famiport/page/cloudprint.aspx'],
    [[/姓名|名子|護照/i, /中翻|英譯|翻譯/], 'https://www.boca.gov.tw/sp-natr-singleform-1.html'],
    [[/蝦皮|shopee|spx/i, '店到店'], 'https://spx.tw'],
    [[/機場捷運|機捷/i, '時刻'], 'https://www.tymetro.com.tw/tymetro-new/tw/_pages/travel-guide/timetable-search.php'],
    [[/顯示卡|顯卡|gpu|nvidia/i, '天梯'], 'https://tieba.baidu.com/p/6133450546'],
    [[/cpu|amd|intel/i, '天梯'], 'https://tieba.baidu.com/p/5005825360'],
    [[/disney|迪士尼/i, /plus|\+/], 'https://www.disneyplus.com/zh-hant/home'],
    [[/mr|mister/i, 'donut'], 'https://www.misterdonut.com.tw'],
    [/^(101)$/i, 'https://www.taipei-101.com.tw'],
    [/^(104|工作)$/i, 'https://www.104.com.tw/jobs/main'],
    [/^(1111)$/i, 'https://www.1111.com.tw'],
    [/^(3+2)$/i, 'https://zip5.5432.tw/zip'],
    [/^(3+3)$/i, 'https://twzipcode.com'],
    [/^(3m)$/i, 'https://shop.3m.com.tw'],
    [/^(55688|taxi)$/, 'https://www.taiwantaxi.com.tw'],
    [/^(711|小7|統一超商|seven)$/i, 'https://www.7-11.com.tw'],
    [/^(7z)$/i, 'https://www.7-zip.org'],
    [/^(8818)$/i, 'https://8818pizza.com.tw'],
    [/^(三冠王|中嘉|雙子星)$/i, 'https://www.homeplus.net.tw/cable'],
    [/^(三洋|sanyo|sanlux)$/i, 'http://www.sanyo.com.tw/'],
    [/^(丸龜)$/i, 'https://www.marukametw.com'],
    [/^(大正製藥)$/i, 'https://www.twtaisho.com.tw'],
    [/^(大哥大|台灣之星)$/, 'https://www.taiwanmobile.com'],
    [/^(大榮)$/i, 'https://www.kerrytj.com/zh'],
    [/^(大潤發)$/i, 'https://www.rt-mart.com.tw'],
    [/^(小北)$/i, 'https://www.showba.com.tw'],
    [/^(小磨坊)$/i, 'https://www.tomax.com.tw'],
    [/^(中天)$/i, 'https://www.youtube.com/channel/UC5l1Yto5oOIgRXlI4p4VKbw'],
    [/^(中油)$/i, 'https://www.cpc.com.tw'],
    [/^(中華電信|cht)$/, 'https://www.cht.com.tw'],
    [/^(天氣)$/i, 'https://www.cwa.gov.tw/V8/C/W/County/index.html'],
    [/^(巴哈)$/i, 'https://www.gamer.com.tw'],
    [/^(日立|hitachi)$/, 'https://www.jci-hitachi.tw/'],
    [/^(火車時刻)$/i, 'https://tw.piliapp.com/tw-railway'],
    [/^(火箭速配|酷澎|coupang)$/, 'https://www.tw.coupang.com'],
    [/^(北捷|捷運)$/, 'https://www.metro.taipei'],
    [/^(台隆|)$/i, 'https://shopping.hands.com.tw/'],
    [/^(台達|delta)$/, 'https://www.deltaww.com/zh-tw/index'],
    [/^(台灣固網|固網)$/, 'https://www.twmsolution.com/internet'],
    [/^(巨匠)$/i, 'https://www.abconline.com.tw/'],
    [/^(巨匠電腦)$/i, 'https://www.pcschool.com.tw//'],
    [/^(必勝客|pizzahut)$/i, 'https://www.pizzahut.com.tw'],
    [/^(立訊)$/i, 'https://www.luxshare-ict.com'],
    [/^(光世代|hinet)$/, 'https://www.hinet.net'],
    [/^(光華)$/i, 'https://www.gh3c.com.tw'],
    [/^(全家|fami)$/, 'https://www.family.com.tw'],
    [/^(全國電子)$/i, 'https://ec.elifemall.com.tw'],
    [/^(全聯|pxmart)$/i, 'https://www.pxmart.com.tw'],
    [/^(吉野家|yoshinoya)$/i, 'https://yoshinoya.com.tw'],
    [/^(好市多|costco)$/, 'https://www.costco.com.tw'],
    [/^(安捷倫)$/i, 'https://www.agilent.com'],
    [/^(百保能)$/i, 'https://www.twtaisho.com.tw/pabron'],
    [/^(宏亞)$/i, 'https://www.hunya.com.tw'],
    [/^(亞太)$/i, 'https://www.aptg.com.tw/my'],
    [/^(京東|jd)$/, 'https://tw.jd.com'],
    [/^(京站)$/i, 'https://www.qsquare.com.tw'],
    [/^(味王)$/i, 'https://www.vewong.com'],
    [/^(和樂|hola)$/, 'https://www.hola.com.tw'],
    [/^(宜家|ikea)$/, 'https://www.ikea.com.tw/zh'],
    [/^(宜得利|nitori)$/, 'https://www.nitori.com.tw'],
    [/^(屈臣氏)$/i, 'https://www.watsons.com.tw'],
    [/^(旺旺)$/i, 'https://shop.want-want.com.tw/products'],
    [/^(松本清)$/i, 'https://www.matsumotokiyoshi-tw.com'],
    [/^(松屋)$/i, 'https://www.matsuyafoods.co.jp/cn/menu'],
    [/^(欣亞)$/i, 'https://www.sinya.com.tw'],
    [/^(欣表飛鳴|表飛鳴)$/, 'https://www.twtaisho.com.tw/biofermin'],
    [/^(油價)$/i, 'https://gas.goodlife.tw'],
    [/^(知乎)$/i, 'https://www.zhihu.com/signin?next=%2F'],
    [/^(肯德基)$/i, 'https://www.kfcclub.com.tw'],
    [/^(虎牌|)$/i, 'https://www.tiger-corporation.tw/'],
    [/^(金石堂|kingstone)$/, 'https://www.kingstone.com.tw'],
    [/^(金車)$/i, 'https://www.kingcar.com.tw/tw/'],
    [/^(阿瘦|aso)$/, 'https://www.aso.com.tw'],
    [/^(南紡)$/i, 'https://www.tsrd.com.tw'],
    [/^(南僑)$/i, 'https://www.namchow.com.tw'],
    [/^(研華)$/i, 'https://www.advantech.com/zh-tw'],
    [/^(紅米|mi|小米)$/, 'https://www.mi.com/tw'],
    [/^(美廉社)$/i, 'https://www.simplemart.com.tw'],
    [/^(若元錠|wakamoto)$/, 'https://www.wakamoto.com.tw/product/index.html'],
    [/^(飛利浦|philips)$/i, 'https://www.philips.com.tw'],
    [/^(原價屋)$/i, 'https://coolpc.com.tw/tw'],
    [/^(唐吉訶德|donki)$/, 'https://www.dondondonki.com/tw'],
    [/^(家樂福)$/i, 'https://online.carrefour.com.tw'],
    [/^(拿坡里)$/i, 'https://www.0800076666.com.tw'],
    [/^(捐血)$/i, 'https://dh.blood.org.tw/donor/index.htm'],
    [/^(特力屋|b&q|trplus)$/, 'https://www.trplus.com.tw'],
    [/^(特福|tefal)$/i, 'https://www.tefal-home.com.tw/tech'],
    [/^(神話言)$/i, 'https://www.talescasashop.com/'],
    [/^(高鐵)$/i, 'https://www.thsrc.com.tw'],
    [/^(商周|商週|商業週刊)$/, 'https://www.businessweekly.com.tw'],
    [/^(康寧|corning)$/i, 'https://www.corning.com/tw/zh_tw.html'],
    [/^(旋轉拍賣)$/i, 'https://tw.carousell.com'],
    [/^(淘寶)$/i, 'https://world.taobao.com'],
    [/^(雀巢|nescafe)$/i, 'https://www.nescafe.com/tw/'],
    [/^(鳥哥)$/i, 'https://linux.vbird.org'],
    [/^(麥當勞)$/i, 'https://www.mcdonalds.com/tw/zh-tw.html'],
    [/^(凱擘|kbro)$/, 'https://www.kbro.com.tw'],
    [/^(勞力士|rolex)$/, 'https://www.rolex.com/zh-hant'],
    [/^(博客來|books)$/, 'https://www.books.com.tw'],
    [/^(替代役)$/i, 'https://www.nca.gov.tw'],
    [/^(測速|fast)$/, 'https://fast.com/zh/tw'],
    [/^(發票)$/i, 'https://invoice.etax.nat.gov.tw'],
    [/^(統一)$/i, 'https://www.uni-president.com.tw'],
    [/^(萊爾富)$/i, 'https://www.hilife.com.tw'],
    [/^(開元食品)$/i, 'https://www.creation.com.tw'],
    [/^(黑橋牌)$/i, 'https://www.blackbridge.com.tw'],
    [/^(黑貓)$/i, 'https://www.t-cat.com.tw'],
    [/^(愛買)$/i, 'https://www.fe-amart.com.tw/'],
    [/^(新東陽)$/i, 'https://www.hty.com.tw'],
    [/^(義美)$/i, 'https://www.imeifoods.com.tw'],
    [/^(誠品)$/i, 'https://www.eslite.com'],
    [/^(遊戲橘子|黑橘|beanfun|gamania)$/i, 'https://tw.beanfun.com/game_zone/'],
    [/^(運彩)$/i, 'https://www.sportslottery.com.tw'],
    [/^(達美樂)$/i, 'https://www.dominos.com.tw'],
    [/^(夢時代)$/i, 'https://www.dreammall.com.tw'],
    [/^(漢神巨蛋)$/i, 'https://www.hanshin.com.tw/%E6%BC%A2%E7%A5%9E%E5%B7%A8%E8%9B%8B/tw'],
    [/^(漢神百貨)$/i, 'https://www.hanshin.com.tw/tw'],
    [/^(漢堡王)$/i, 'https://www.burgerking.com.tw'],
    [/^(精工|seiko)$/, 'https://www.seikowatches.com/tw-zh'],
    [/^(網飛|netflix)$/i, 'https://www.netflix.com/tw/'],
    [/^(網路家庭|網家|pchome)$/i, 'https://24h.pchome.com.tw'],
    [/^(遠百|遠東百貨)$/, 'https://www.feds.com.tw'],
    [/^(遠傳)$/i, 'https://www.fetnet.net'],
    [/^(領英|linkedin)$/, 'https://tw.linkedin.com'],
    [/^(導航王|localking)$/i, 'https://naviking.localking.com.tw'],
    [/^(摩斯|mos)$/, 'https://www.mos.com.tw'],
    [/^(樂天|rakuten)$/i, 'https://www.rakuten.com.tw'],
    [/^(歐姆龍|omron)$/i, 'https://www.omronhealthcare.com.tw/'],
    [/^(潛艇堡|subway)$/, 'https://subway.com.tw'],
    [/^(蝦皮|shopee)$/i, 'https://shopee.tw'],
    [/^(論文)$/i, 'https://ndltd.ncl.edu.tw/cgi-bin/gs32/gsweb.cgi?o=d'],
    [/^(鞋全家福)$/i, 'https://www.familyshoes.com.tw'],
    [/^(機捷)$/i, 'https://www.tymetro.com.tw/tymetro-new/tw/index.php'],
    [/^(膳魔師|THERMOS)$/i, 'https://www.thermos.com.tw/index.aspx'],
    [/^(戴森|dyson)$/, 'https://www.dyson.tw'],
    [/^(燦坤)$/i, 'https://www.tk3c.com/'],
    [/^(環球購物)$/i, 'https://www.twglobalmall.com'],
    [/^(鴻海)$/i, 'https://www.foxconn.com'],
    [/^(職棒)$/i, 'https://www.cpbl.com.tw'],
    [/^(寵物公園)$/i, 'https://www.wonderpet.asia'],
    [/^(繳費)$/i, 'https://ebill.ba.org.tw'],
    [/^(寶雅|poya)$/, 'https://www.poyabuy.com.tw'],
    [/^(護照)$/i, 'https://www.boca.gov.tw/np-1-1.html'],
    [/^(露天|ruten)$/, 'https://www.ruten.com.tw'],
    [/^(驍龍|snapdragon)$/, 'https://www.qualcomm.cn/snapdragon/detail'],
    [/^(adidas|愛迪達)$/i, 'https://www.adidas.com.tw/'],
    [/^(aeon)$/i, 'https://tw.aeonmall.global'],
    [/^(agilent)$/i, 'https://www.agilent.com/'],
    [/^(amiibo)$/i, 'https://www.nintendo.tw/amiibo/'],
    [/^(animate)$/i, 'https://www.animate-onlineshop.com.tw/'],
    [/^(apktw)$/i, 'https://apk.tw/forum.php'],
    [/^(asics|亞瑟士)$/i, 'https://www.asics.com.tw/?lang=zh-TW'],
    [/^(BALMUDA)$/i, 'https://www.balmuda.com.tw/'],
    [/^(bbc)$/i, 'https://www.bbc.com'],
    [/^(bilibili)$/i, 'https://www.bilibili.com'],
    [/^(cartier)$/i, 'https://www.cartier.com/zh-tw/home'],
    [/^(casio)$/i, 'https://www.casio.com/tw'],
    [/^(chanel)$/i, 'https://www.chanel.com/tw'],
    [/^(citizen)$/i, 'https://www.citizenwatch.com.tw'],
    [/^(ck)$/i, 'https://www.calvinklein.com.tw/zh/home'],
    [/^(coco)$/i, 'https://www.facebook.com/cocofreshtea.tw'],
    [/^(Columbia)$/i, 'https://www.columbiasportswear.com.tw/?lang=zh-TW'],
    [/^(converse|匡威)$/i, 'https://www.converse.com.tw/'],
    [/^(dcard)$/i, 'https://www.dcard.tw'],
    [/^(Decathlon|迪卡儂)$/i, 'https://decathlon.tw'],
    [/^(desmos)$/i, 'https://www.desmos.com/calculator'],
    [/^(discord)$/i, 'https://discord.com'],
    [/^(disney|迪士尼)$/i, 'https://www.disney.com.tw'],
    [/^(duckduck)$/i, 'https://duckduckgo.com'],
    [/^(e7play)$/i, 'https://www.e7play.com.tw/'],
    [/^(ea)$/i, 'https://www.ea.com/zh-tw'],
    [/^(ebay)$/i, 'https://www.ebay.com/'],
    [/^(ECOVACS|科沃斯)$/i, 'https://www.ecovacs.com/tw'],
    [/^(edion)$/i, 'https://www.edion.co.jp/zh-CHT'],
    [/^(electrolux|伊萊克斯)$/i, 'https://www.electrolux.com.tw/'],
    [/^(electron)$/i, 'https://www.electronjs.org/docs/latest'],
    [/^(etag)$/i, 'https://www.fetc.net.tw'],
    [/^(etmall)$/i, 'https://www.etmall.com.tw'],
    [/^(fcc)$/i, 'https://www.fcc.gov'],
    [/^(feedly)$/i, 'https://feedly.com/i/my'],
    [/^(fila|斐樂)$/i, 'https://www.fila.com.tw/'],
    [/^(filecr)$/i, 'https://filecr.com'],
    [/^(fluke)$/i, 'https://www.fluke.com/zh-tw'],
    [/^(foodpanda)$/i, 'https://www.foodpanda.com.tw'],
    [/^(friday)$/i, 'https://shopping.friday.tw'],
    [/^(fridays|tgi)$/, 'https://www.tgifridays.com.tw'],
    [/^(gdaily)$/i, 'https://www.gdaily.org'],
    [/^(golang)$/i, 'https://go.dev'],
    [/^(Gregory)$/i, 'https://www.gregory.com/'],
    [/^(gsync)$/i, 'https://www.nvidia.com/zh-tw/geforce/products/g-sync-monitors/'],
    [/^(gtx)$/i, 'https://www.nvidia.com/zh-tw/geforce/graphics-cards'],
    [/^(gu)$/i, 'https://www.gu-global.com/tw/zh_TW'],
    [/^(h&m|hm)$/, 'https://www2.hm.com/zh_asia3/index.html'],
    [/^(hilltop|山頂鳥)$/i, 'https://www.e-hilltop.com/?lang=zh-TW'],
    [/^(Hoka ?One ?One)$/i, 'https://www.momentum.com.tw/'],
    [/^(htmlx)$/i, 'https://htmx.org/'],
    [/^(hueiyeh|輝葉)$/i, 'https://www.hueiyeh.com.tw/product.php'],
    [/^(ibon)$/i, 'https://print.ibon.com.tw/ibonprinter'],
    [/^(icash)$/i, 'https://www.icash.com.tw'],
    [/^(ig|instagram)$/, 'https://www.instagram.com'],
    [/^(ipv6)$/i, 'https://test-ipv6.com/index.html.zh_TW'],
    [/^(jog)$/i, 'https://www.yamaha-motor.com.tw/motor/motor_JOG'],
    [/^(kinyo)$/i, 'https://www.kinyo.tw'],
    [/^(kirin)$/i, 'https://www.kirin.com.tw/'],
    [/^(Levi'?s|李維斯)$/i, 'https://www.levis.com.tw/'],
    [/^(linksys)$/i, 'https://www.linksys.com/tw'],
    [/^(localking)$/i, 'https://www.localking.com.tw'],
    [/^(lol)$/i, 'https://www.leagueoflegends.com/zh-tw'],
    [/^(lulu ?lemon|露露檸檬)$/i, 'https://www.lulu-lemon.com.tw/'],
    [/^(lv)$/i, 'https://tw.louisvuitton.com/zht-tw/homepage'],
    [/^(meta)$/i, 'https://www.meta.com/'],
    [/^(Mizuno|美津濃)$/i, 'https://twn.mizuno.com/'],
    [/^(mobile01)$/i, 'https://www.mobile01.com'],
    [/^(momo)$/i, 'https://www.momoshop.com.tw/main/Main.jsp'],
    [/^(money101)$/i, 'https://www.money101.com.tw'],
    [/^(Mountain ?Hardwear)$/i, 'https://www.mountainhardwear.com/'],
    [/^(muji|無印|無印良品)$/i, 'https://shop.muji.tw/?lang=zh-TW'],
    [/^(myip)$/i, 'https://browserleaks.com/ip'],
    [/^(nespresso)$/i, 'https://www.nespresso.com/tw/'],
    [/^(New ?Balance|nb)$/i, 'https://www.newbalance.com.tw/'],
    [/^(nike)$/i, 'https://www.nike.com/tw/'],
    [/^(notion)$/i, 'https://www.notion.so'],
    [/^(npm)$/i, 'https://www.npmjs.com'],
    [/^(OK)$/i, 'https://www.okmart.com.tw'],
    [/^(omega)$/i, 'https://www.omegawatches.com.tw'],
    [/^(one ?boy)$/i, 'https://www.oneboy.com.tw/'],
    [/^(Onitsuka ?Tiger|鬼塚虎)$/i, 'https://www.onitsukatiger.com.tw/'],
    [/^(Osprey)$/i, 'https://www.osprey.com/tw/en'],
    [/^(otterbox)$/i, 'https://otterbox.shopstore.tw/category/otterboxcase'],
    [/^(pandago)$/i, 'https://www.foodpanda.com.tw/contents/pandago'],
    [/^(papago)$/i, 'https://www.papagoinc.com/products/GPSnavi.aspx'],
    [/^(Patagonia)$/i, 'https://www.patagoniatw.com.tw/'],
    [/^(pony|波尼)$/i, 'https://www.ponytaiwan.com.tw/?lang=zh-TW'],
    [/^(proart)$/i, 'https://www.asus.com/tw/proart/'],
    [/^(ptt)$/i, 'https://term.ptt.cc'],
    [/^(puma)$/i, 'https://tw.puma.com/?lang=zh-TW'],
    [/^(qti)$/i, 'https://createpoint.qti.qualcomm.com'],
    [/^(reebok|銳跑)$/i, 'https://www.reebok.com.tw/'],
    [/^(rog)$/i, 'https://rog.asus.com/tw/'],
    [/^(sandisk|晟碟|閃迪)$/i, 'https://www.westerndigital.com/zh-tw/brand/sandisk'],
    [/^(scrum)$/i, 'https://www.scrum.org/'],
    [/^(shopback)$/i, 'https://www.shopback.com.tw'],
    [/^(Skechers|斯凱奇)$/i, 'https://www.skechers-twn.com/'],
    [/^(speedtest)$/i, 'https://www.speedtest.net/zh-Hant'],
    [/^(steam)$/i, 'https://store.steampowered.com/?l=tchinese'],
    [/^(swatch)$/i, 'https://www.swatch.com/zh-tw'],
    [/^(switch)$/i, 'https://www.nintendo.tw/hardware/switch/'],
    [/^(tampermonkey|userscript)$/, 'https://www.tampermonkey.net'],
    [/^(tbc)$/i, 'https://www.tbc.net.tw/Index'],
    [/^(timberland)$/i, 'https://www.timberland.com.tw/?lang=zh-TW'],
    [/^(tpass)$/i, 'https://www.i-pass.com.tw/Page/TPASScard'],
    [/^(tsmc)$/i, 'https://www.tsmc.com/chinese'],
    [/^(tuf)$/i, 'https://www.asus.com/tw/laptops/for-gaming/tuf-gaming/'],
    [/^(uber)$/i, 'https://www.uber.com/tw/zh-tw'],
    [/^(ugreen|綠聯)$/i, 'https://www.ugreen.com/'],
    [/^(Umbro)$/i, 'https://www.umbro.com/en/'],
    [/^(Under ?Armour|UA)$/i, 'https://www.underarmour.tw/'],
    [/^(uniqlo)$/i, 'https://www.uniqlo.com/tw/zh_TW'],
    [/^(vans)$/i, 'https://www.vans-shop.com.tw'],
    [/^(webpack)$/i, 'https://webpack.js.org'],
    [/^(wii)$/i, 'https://www.nintendo.tw/wii/wii_software.html'],
    [/^(wiki)$/i, 'https://zh.wikipedia.org/wiki'],
    [/^(winrar)$/i, 'https://www.rarlab.com/download.htm'],
    [/^(wolfram)$/i, 'https://www.wolframalpha.com'],
    [/^(yahoo)$/i, 'https://tw.yahoo.com'],
    [/^(youtube|utube)$/i, 'https://www.youtube.com'],
    [/^(zenbook)$/i, 'https://www.asus.com/tw/laptops/for-home/zenbook'],
    [/^(zenfone)$/i, 'https://www.asus.com/tw/mobile-handhelds/phones/zenfone/'],
    [/^(ZOJIRUSHI|象印)$/i, 'https://www.zojirushi.com.tw/'],
    [/^上下游(新聞)?|newsmarket$/i, 'https://www.newsmarket.com.tw/'],
    [/^食力|foodnext$/i, 'https://www.foodnext.net/'],
    [/^動畫(風|瘋)$/i, 'https://ani.gamer.com.tw/'],
    [/^電玩(風|瘋)$/i, 'https://gnn.gamer.com.tw/gamecrazy.php/'],
    [/^arduino$/i, 'https://www.arduino.cc/'],
    [/^chatgpt$/i, 'https://chat.openai.com'],
    [/^ieee$/i, 'https://ieeexplore.ieee.org/Xplore/home.jsp'],
    [/^k-?swiss$/i, 'https://www.k-swiss.com.tw/'],
    [/^Palladium$/i, 'https://www.palladium.com.tw/'],
    [/^r(a|e)spberry( ?pi)?$/i, 'https://www.raspberrypi.com/'],
    [/^tvbs$/i, 'https://www.tvbs.com.tw'],
    [/交貨便/i, 'https://myship.7-11.com.tw'],
    [/mammut/i, 'https://www.mammut.tw/'],
    [/Marmot/i, 'https://www.marmot.com/'],
    [/North ?Face|北臉/i, 'https://www.thenorthface.com.tw/?lang=zh-TW'],
  ]

  function goReplace() {
    const url = new URL(location.href)
    const params = new URLSearchParams(url.search)
    const keepValue = params.get('q').toLocaleLowerCase().replace('臺', '台')

    const matchedItem = KEYWORDS.find((item) => {
      // 如果 item[0] 為陣列
      if (item[0] instanceof Array) {
        return item[0].every((subitem) => {
          if (subitem instanceof RegExp) return subitem.test(keepValue) // 若陣列元素為 regexp
          return subitem.toLowerCase().includes(keepValue) || keepValue.includes(subitem)
        })
      }
      // 如果 item[0] 不為陣列
      if (item[0] instanceof RegExp) return item[0].test(keepValue) // 若 item[0] 為 regexp，直接測試

      // 完全 match
      if (typeof item[0] === 'string') return item[0].toLowerCase() === keepValue
    })

    console.log(matchedItem)
    location.href = matchedItem[1]
  }

  goReplace()
})()
